// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.240405.15

#pragma once
#include "winrt/SDKTemplate.h"
#include "winrt/Windows.UI.Xaml.Data.h"
namespace winrt::SDKTemplate::implementation
{
    template <typename D, typename... I>
    struct WINRT_IMPL_EMPTY_BASES BluetoothLEDeviceDisplay_base : implements<D, SDKTemplate::BluetoothLEDeviceDisplay, winrt::Windows::UI::Xaml::Data::INotifyPropertyChanged, I...>
    {
        using base_type = BluetoothLEDeviceDisplay_base;
        using class_type = SDKTemplate::BluetoothLEDeviceDisplay;
        using implements_type = typename BluetoothLEDeviceDisplay_base::implements_type;
        using implements_type::implements_type;
        
        hstring GetRuntimeClassName() const
        {
            return L"SDKTemplate.BluetoothLEDeviceDisplay";
        }
    };
}

#if defined(WINRT_FORCE_INCLUDE_BLUETOOTHLEDEVICEDISPLAY_XAML_G_H) || __has_include("BluetoothLEDeviceDisplay.xaml.g.h")

#include "BluetoothLEDeviceDisplay.xaml.g.h"

#else

namespace winrt::SDKTemplate::implementation
{
    template <typename D, typename... I>
    using BluetoothLEDeviceDisplayT = BluetoothLEDeviceDisplay_base<D, I...>;
}

#endif
