// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.240405.15

void* winrt_make_SDKTemplate_CalculatorServerBackgroundTask()
{
    return winrt::detach_abi(winrt::make<winrt::SDKTemplate::factory_implementation::CalculatorServerBackgroundTask>());
}
WINRT_EXPORT namespace winrt::SDKTemplate
{
    CalculatorServerBackgroundTask::CalculatorServerBackgroundTask() :
        CalculatorServerBackgroundTask(make<SDKTemplate::implementation::CalculatorServerBackgroundTask>())
    {
    }
}
