//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#pragma once


namespace winrt::SDKTemplate::implementation
{
    using IInspectable = ::winrt::Windows::Foundation::IInspectable;

    template <typename D, typename ... I>
    struct Scenario3_ServerForegroundT : public ::winrt::SDKTemplate::implementation::Scenario3_ServerForeground_base<D,
        ::winrt::Windows::UI::Xaml::Markup::IComponentConnector,
        ::winrt::Windows::UI::Xaml::Markup::IComponentConnector2,
        I...>
    {
        using base_type = typename Scenario3_ServerForegroundT::base_type;
        using base_type::base_type;
        using class_type = typename Scenario3_ServerForegroundT::class_type;

        void InitializeComponent();
        virtual void Connect(int32_t connectionId, IInspectable const& target);
        virtual ::winrt::Windows::UI::Xaml::Markup::IComponentConnector GetBindingConnector(int32_t connectionId, IInspectable const& target);
        void UnloadObject(::winrt::Windows::UI::Xaml::DependencyObject const& dependencyObject);
        void DisconnectUnloadedObject(int32_t connectionId);

        ::winrt::Windows::UI::Xaml::Controls::TextBlock PeripheralWarning()
        {
            return _PeripheralWarning;
        }
        void PeripheralWarning(::winrt::Windows::UI::Xaml::Controls::TextBlock value)
        {
            _PeripheralWarning = value;
        }

        ::winrt::Windows::UI::Xaml::Controls::StackPanel ServerPanel()
        {
            return _ServerPanel;
        }
        void ServerPanel(::winrt::Windows::UI::Xaml::Controls::StackPanel value)
        {
            _ServerPanel = value;
        }

        ::winrt::Windows::UI::Xaml::Controls::CheckBox Publishing2MPHY()
        {
            return _Publishing2MPHY;
        }
        void Publishing2MPHY(::winrt::Windows::UI::Xaml::Controls::CheckBox value)
        {
            _Publishing2MPHY = value;
        }

        ::winrt::Windows::UI::Xaml::Controls::Button PublishButton()
        {
            return _PublishButton;
        }
        void PublishButton(::winrt::Windows::UI::Xaml::Controls::Button value)
        {
            _PublishButton = value;
        }

        ::winrt::Windows::UI::Xaml::Controls::TextBox ResultTextBox()
        {
            return _ResultTextBox;
        }
        void ResultTextBox(::winrt::Windows::UI::Xaml::Controls::TextBox value)
        {
            _ResultTextBox = value;
        }

        ::winrt::Windows::UI::Xaml::Controls::TextBlock ResultLabel()
        {
            return _ResultLabel;
        }
        void ResultLabel(::winrt::Windows::UI::Xaml::Controls::TextBlock value)
        {
            _ResultLabel = value;
        }

        ::winrt::Windows::UI::Xaml::Controls::TextBox Operand2TextBox()
        {
            return _Operand2TextBox;
        }
        void Operand2TextBox(::winrt::Windows::UI::Xaml::Controls::TextBox value)
        {
            _Operand2TextBox = value;
        }

        ::winrt::Windows::UI::Xaml::Controls::TextBlock Operand2Label()
        {
            return _Operand2Label;
        }
        void Operand2Label(::winrt::Windows::UI::Xaml::Controls::TextBlock value)
        {
            _Operand2Label = value;
        }

        ::winrt::Windows::UI::Xaml::Controls::TextBox OperationTextBox()
        {
            return _OperationTextBox;
        }
        void OperationTextBox(::winrt::Windows::UI::Xaml::Controls::TextBox value)
        {
            _OperationTextBox = value;
        }

        ::winrt::Windows::UI::Xaml::Controls::TextBlock OperationLabel()
        {
            return _OperationLabel;
        }
        void OperationLabel(::winrt::Windows::UI::Xaml::Controls::TextBlock value)
        {
            _OperationLabel = value;
        }

        ::winrt::Windows::UI::Xaml::Controls::TextBox Operand1TextBox()
        {
            return _Operand1TextBox;
        }
        void Operand1TextBox(::winrt::Windows::UI::Xaml::Controls::TextBox value)
        {
            _Operand1TextBox = value;
        }

        ::winrt::Windows::UI::Xaml::Controls::TextBlock Operand1Label()
        {
            return _Operand1Label;
        }
        void Operand1Label(::winrt::Windows::UI::Xaml::Controls::TextBlock value)
        {
            _Operand1Label = value;
        }

        ::winrt::Windows::UI::Xaml::Documents::Run Publishing2MPHYReasonRun()
        {
            return _Publishing2MPHYReasonRun;
        }
        void Publishing2MPHYReasonRun(::winrt::Windows::UI::Xaml::Documents::Run value)
        {
            _Publishing2MPHYReasonRun = value;
        }

        ::winrt::Windows::UI::Xaml::Documents::Run ServiceIdRun()
        {
            return _ServiceIdRun;
        }
        void ServiceIdRun(::winrt::Windows::UI::Xaml::Documents::Run value)
        {
            _ServiceIdRun = value;
        }
        
    protected:
        bool _contentLoaded{false};

    private:
        struct Scenario3_ServerForeground_obj1_Bindings;

        ::winrt::Windows::UI::Xaml::Controls::TextBlock _PeripheralWarning{nullptr};
        ::winrt::Windows::UI::Xaml::Controls::StackPanel _ServerPanel{nullptr};
        ::winrt::Windows::UI::Xaml::Controls::CheckBox _Publishing2MPHY{nullptr};
        ::winrt::Windows::UI::Xaml::Controls::Button _PublishButton{nullptr};
        ::winrt::Windows::UI::Xaml::Controls::TextBox _ResultTextBox{nullptr};
        ::winrt::Windows::UI::Xaml::Controls::TextBlock _ResultLabel{nullptr};
        ::winrt::Windows::UI::Xaml::Controls::TextBox _Operand2TextBox{nullptr};
        ::winrt::Windows::UI::Xaml::Controls::TextBlock _Operand2Label{nullptr};
        ::winrt::Windows::UI::Xaml::Controls::TextBox _OperationTextBox{nullptr};
        ::winrt::Windows::UI::Xaml::Controls::TextBlock _OperationLabel{nullptr};
        ::winrt::Windows::UI::Xaml::Controls::TextBox _Operand1TextBox{nullptr};
        ::winrt::Windows::UI::Xaml::Controls::TextBlock _Operand1Label{nullptr};
        ::winrt::Windows::UI::Xaml::Documents::Run _Publishing2MPHYReasonRun{nullptr};
        ::winrt::Windows::UI::Xaml::Documents::Run _ServiceIdRun{nullptr};
    };
}

