// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.240405.15

void* winrt_make_SDKTemplate_Scenario1_Discovery()
{
    return winrt::detach_abi(winrt::make<winrt::SDKTemplate::factory_implementation::Scenario1_Discovery>());
}
WINRT_EXPORT namespace winrt::SDKTemplate
{
    Scenario1_Discovery::Scenario1_Discovery() :
        Scenario1_Discovery(make<SDKTemplate::implementation::Scenario1_Discovery>())
    {
    }
}
