//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#pragma once

#include "XamlBindingInfo.xaml.g.h"

namespace winrt::SDKTemplate::implementation
{
    using IInspectable = ::winrt::Windows::Foundation::IInspectable;

    template <typename D, typename ... I>
    struct Scenario1_DiscoveryT : public ::winrt::SDKTemplate::implementation::Scenario1_Discovery_base<D,
        ::winrt::Windows::UI::Xaml::Markup::IComponentConnector,
        ::winrt::Windows::UI::Xaml::Markup::IComponentConnector2,
        I...>
    {
        using base_type = typename Scenario1_DiscoveryT::base_type;
        using base_type::base_type;
        using class_type = typename Scenario1_DiscoveryT::class_type;

        void InitializeComponent();
        virtual void Connect(int32_t connectionId, IInspectable const& target);
        virtual ::winrt::Windows::UI::Xaml::Markup::IComponentConnector GetBindingConnector(int32_t connectionId, IInspectable const& target);
        void UnloadObject(::winrt::Windows::UI::Xaml::DependencyObject const& dependencyObject);
        void DisconnectUnloadedObject(int32_t connectionId);

        ::winrt::Windows::UI::Xaml::Controls::ListView ResultsListView()
        {
            return _ResultsListView;
        }
        void ResultsListView(::winrt::Windows::UI::Xaml::Controls::ListView value)
        {
            _ResultsListView = value;
        }

        ::winrt::Windows::UI::Xaml::Controls::Button EnumerateButton()
        {
            return _EnumerateButton;
        }
        void EnumerateButton(::winrt::Windows::UI::Xaml::Controls::Button value)
        {
            _EnumerateButton = value;
        }

        ::winrt::Windows::UI::Xaml::Controls::Button PairButton()
        {
            return _PairButton;
        }
        void PairButton(::winrt::Windows::UI::Xaml::Controls::Button value)
        {
            _PairButton = value;
        }
        
         ::winrt::com_ptr<::winrt::SDKTemplate::implementation::XamlBindings> Bindings;

    protected:
        bool _contentLoaded{false};

    private:
        struct Scenario1_Discovery_obj3_Bindings;
        struct Scenario1_Discovery_obj1_Bindings;

        ::winrt::Windows::UI::Xaml::Controls::ListView _ResultsListView{nullptr};
        ::winrt::Windows::UI::Xaml::Controls::Button _EnumerateButton{nullptr};
        ::winrt::Windows::UI::Xaml::Controls::Button _PairButton{nullptr};
    };
}

