// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.240405.15

void* winrt_make_SDKTemplate_Scenario3_ServerForeground()
{
    return winrt::detach_abi(winrt::make<winrt::SDKTemplate::factory_implementation::Scenario3_ServerForeground>());
}
WINRT_EXPORT namespace winrt::SDKTemplate
{
    Scenario3_ServerForeground::Scenario3_ServerForeground() :
        Scenario3_ServerForeground(make<SDKTemplate::implementation::Scenario3_ServerForeground>())
    {
    }
}
