//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#pragma once


namespace winrt::SDKTemplate::implementation
{
    using IInspectable = ::winrt::Windows::Foundation::IInspectable;

    template <typename D, typename ... I>
    struct Scenario2_ClientT : public ::winrt::SDKTemplate::implementation::Scenario2_Client_base<D,
        ::winrt::Windows::UI::Xaml::Markup::IComponentConnector,
        ::winrt::Windows::UI::Xaml::Markup::IComponentConnector2,
        I...>
    {
        using base_type = typename Scenario2_ClientT::base_type;
        using base_type::base_type;
        using class_type = typename Scenario2_ClientT::class_type;

        void InitializeComponent();
        virtual void Connect(int32_t connectionId, IInspectable const& target);
        virtual ::winrt::Windows::UI::Xaml::Markup::IComponentConnector GetBindingConnector(int32_t connectionId, IInspectable const& target);
        void UnloadObject(::winrt::Windows::UI::Xaml::DependencyObject const& dependencyObject);
        void DisconnectUnloadedObject(int32_t connectionId);

        ::winrt::Windows::UI::Xaml::Controls::Button ConnectButton()
        {
            return _ConnectButton;
        }
        void ConnectButton(::winrt::Windows::UI::Xaml::Controls::Button value)
        {
            _ConnectButton = value;
        }

        ::winrt::Windows::UI::Xaml::Controls::ComboBox ServiceList()
        {
            return _ServiceList;
        }
        void ServiceList(::winrt::Windows::UI::Xaml::Controls::ComboBox value)
        {
            _ServiceList = value;
        }

        ::winrt::Windows::UI::Xaml::Controls::ComboBox CharacteristicList()
        {
            return _CharacteristicList;
        }
        void CharacteristicList(::winrt::Windows::UI::Xaml::Controls::ComboBox value)
        {
            _CharacteristicList = value;
        }

        ::winrt::Windows::UI::Xaml::Controls::StackPanel CharacteristicWritePanel()
        {
            return _CharacteristicWritePanel;
        }
        void CharacteristicWritePanel(::winrt::Windows::UI::Xaml::Controls::StackPanel value)
        {
            _CharacteristicWritePanel = value;
        }

        ::winrt::Windows::UI::Xaml::Controls::TextBlock CharacteristicLatestValue()
        {
            return _CharacteristicLatestValue;
        }
        void CharacteristicLatestValue(::winrt::Windows::UI::Xaml::Controls::TextBlock value)
        {
            _CharacteristicLatestValue = value;
        }

        ::winrt::Windows::UI::Xaml::Controls::TextBox CharacteristicWriteValue()
        {
            return _CharacteristicWriteValue;
        }
        void CharacteristicWriteValue(::winrt::Windows::UI::Xaml::Controls::TextBox value)
        {
            _CharacteristicWriteValue = value;
        }

        ::winrt::Windows::UI::Xaml::Controls::Button CharacteristicReadButton()
        {
            return _CharacteristicReadButton;
        }
        void CharacteristicReadButton(::winrt::Windows::UI::Xaml::Controls::Button value)
        {
            _CharacteristicReadButton = value;
        }

        ::winrt::Windows::UI::Xaml::Controls::Button ValueChangedSubscribeToggle()
        {
            return _ValueChangedSubscribeToggle;
        }
        void ValueChangedSubscribeToggle(::winrt::Windows::UI::Xaml::Controls::Button value)
        {
            _ValueChangedSubscribeToggle = value;
        }

        ::winrt::Windows::UI::Xaml::Documents::Run SelectedDeviceRun()
        {
            return _SelectedDeviceRun;
        }
        void SelectedDeviceRun(::winrt::Windows::UI::Xaml::Documents::Run value)
        {
            _SelectedDeviceRun = value;
        }
        
    protected:
        bool _contentLoaded{false};

    private:
        struct Scenario2_Client_obj1_Bindings;

        ::winrt::Windows::UI::Xaml::Controls::Button _ConnectButton{nullptr};
        ::winrt::Windows::UI::Xaml::Controls::ComboBox _ServiceList{nullptr};
        ::winrt::Windows::UI::Xaml::Controls::ComboBox _CharacteristicList{nullptr};
        ::winrt::Windows::UI::Xaml::Controls::StackPanel _CharacteristicWritePanel{nullptr};
        ::winrt::Windows::UI::Xaml::Controls::TextBlock _CharacteristicLatestValue{nullptr};
        ::winrt::Windows::UI::Xaml::Controls::TextBox _CharacteristicWriteValue{nullptr};
        ::winrt::Windows::UI::Xaml::Controls::Button _CharacteristicReadButton{nullptr};
        ::winrt::Windows::UI::Xaml::Controls::Button _ValueChangedSubscribeToggle{nullptr};
        ::winrt::Windows::UI::Xaml::Documents::Run _SelectedDeviceRun{nullptr};
    };
}

