// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.240405.15

void* winrt_make_SDKTemplate_Scenario4_ServerBackground()
{
    return winrt::detach_abi(winrt::make<winrt::SDKTemplate::factory_implementation::Scenario4_ServerBackground>());
}
WINRT_EXPORT namespace winrt::SDKTemplate
{
    Scenario4_ServerBackground::Scenario4_ServerBackground() :
        Scenario4_ServerBackground(make<SDKTemplate::implementation::Scenario4_ServerBackground>())
    {
    }
}
