// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.240405.15

void* winrt_make_SDKTemplate_XamlMetaDataProvider()
{
    return winrt::detach_abi(winrt::make<winrt::SDKTemplate::factory_implementation::XamlMetaDataProvider>());
}
WINRT_EXPORT namespace winrt::SDKTemplate
{
    XamlMetaDataProvider::XamlMetaDataProvider() :
        XamlMetaDataProvider(make<SDKTemplate::implementation::XamlMetaDataProvider>())
    {
    }
}
