//------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by cswinrt.exe version 2.3.0-prerelease.250720.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace WinRT
{

    internal sealed unsafe class _EventSource_global__Windows_Foundation_TypedEventHandler_global__Windows_Devices_Bluetooth_GenericAttributeProfile_GattSession__object_ : global::ABI.WinRT.Interop.EventSource<global::Windows.Foundation.TypedEventHandler<global::Windows.Devices.Bluetooth.GenericAttributeProfile.GattSession, object>>
    {
        private static readonly bool initialized = global::WinRT.GenericTypeInstantiations.Windows_Foundation_TypedEventHandler_2_Windows_Devices_Bluetooth_GenericAttributeProfile_GattSession__object.EnsureInitialized();

        internal _EventSource_global__Windows_Foundation_TypedEventHandler_global__Windows_Devices_Bluetooth_GenericAttributeProfile_GattSession__object_(IObjectReference obj,
        delegate* unmanaged[Stdcall]<System.IntPtr, System.IntPtr, WinRT.EventRegistrationToken*, int> addHandler,
        delegate* unmanaged[Stdcall]<System.IntPtr, WinRT.EventRegistrationToken, int> removeHandler, int index) : base(obj, addHandler, removeHandler, index)
        {
            _ = initialized;
        }

        protected override ObjectReferenceValue CreateMarshaler(global::Windows.Foundation.TypedEventHandler<global::Windows.Devices.Bluetooth.GenericAttributeProfile.GattSession, object> handler) =>
        global::ABI.Windows.Foundation.TypedEventHandler<global::Windows.Devices.Bluetooth.GenericAttributeProfile.GattSession, object>.CreateMarshaler2(handler);

        protected override global::ABI.WinRT.Interop.EventSourceState<global::Windows.Foundation.TypedEventHandler<global::Windows.Devices.Bluetooth.GenericAttributeProfile.GattSession, object>> CreateEventSourceState() =>
        new EventState(ObjectReference.ThisPtr, Index);

        [global::WinRT.WinRTExposedType]
        private sealed class EventState : global::ABI.WinRT.Interop.EventSourceState<global::Windows.Foundation.TypedEventHandler<global::Windows.Devices.Bluetooth.GenericAttributeProfile.GattSession, object>>
        {
            public EventState(System.IntPtr obj, int index)
            : base(obj, index)
            {
            }

            protected override global::Windows.Foundation.TypedEventHandler<global::Windows.Devices.Bluetooth.GenericAttributeProfile.GattSession, object> GetEventInvoke()
            {
                return (global::Windows.Devices.Bluetooth.GenericAttributeProfile.GattSession sender, object args) =>
                {
                    var targetDelegate = TargetDelegate;
                    if (targetDelegate is null)
                    {
                        return ;
                    }
                    targetDelegate.Invoke(sender, args);
                };
            }
        }
    }

    internal sealed unsafe class _EventSource_global__Windows_Foundation_TypedEventHandler_global__Windows_Devices_Bluetooth_Advertisement_BluetoothLEAdvertisementWatcher__global__Windows_Devices_Bluetooth_Advertisement_BluetoothLEAdvertisementWatcherStoppedEventArgs_ : global::ABI.WinRT.Interop.EventSource<global::Windows.Foundation.TypedEventHandler<global::Windows.Devices.Bluetooth.Advertisement.BluetoothLEAdvertisementWatcher, global::Windows.Devices.Bluetooth.Advertisement.BluetoothLEAdvertisementWatcherStoppedEventArgs>>
    {
        private static readonly bool initialized = global::WinRT.GenericTypeInstantiations.Windows_Foundation_TypedEventHandler_2_Windows_Devices_Bluetooth_Advertisement_BluetoothLEAdvertisementWatcher__Windows_Devices_Bluetooth_Advertisement_BluetoothLEAdvertisementWatcherStoppedEventArgs.EnsureInitialized();

        internal _EventSource_global__Windows_Foundation_TypedEventHandler_global__Windows_Devices_Bluetooth_Advertisement_BluetoothLEAdvertisementWatcher__global__Windows_Devices_Bluetooth_Advertisement_BluetoothLEAdvertisementWatcherStoppedEventArgs_(IObjectReference obj,
        delegate* unmanaged[Stdcall]<System.IntPtr, System.IntPtr, WinRT.EventRegistrationToken*, int> addHandler,
        delegate* unmanaged[Stdcall]<System.IntPtr, WinRT.EventRegistrationToken, int> removeHandler, int index) : base(obj, addHandler, removeHandler, index)
        {
            _ = initialized;
        }

        protected override ObjectReferenceValue CreateMarshaler(global::Windows.Foundation.TypedEventHandler<global::Windows.Devices.Bluetooth.Advertisement.BluetoothLEAdvertisementWatcher, global::Windows.Devices.Bluetooth.Advertisement.BluetoothLEAdvertisementWatcherStoppedEventArgs> handler) =>
        global::ABI.Windows.Foundation.TypedEventHandler<global::Windows.Devices.Bluetooth.Advertisement.BluetoothLEAdvertisementWatcher, global::Windows.Devices.Bluetooth.Advertisement.BluetoothLEAdvertisementWatcherStoppedEventArgs>.CreateMarshaler2(handler);

        protected override global::ABI.WinRT.Interop.EventSourceState<global::Windows.Foundation.TypedEventHandler<global::Windows.Devices.Bluetooth.Advertisement.BluetoothLEAdvertisementWatcher, global::Windows.Devices.Bluetooth.Advertisement.BluetoothLEAdvertisementWatcherStoppedEventArgs>> CreateEventSourceState() =>
        new EventState(ObjectReference.ThisPtr, Index);

        [global::WinRT.WinRTExposedType]
        private sealed class EventState : global::ABI.WinRT.Interop.EventSourceState<global::Windows.Foundation.TypedEventHandler<global::Windows.Devices.Bluetooth.Advertisement.BluetoothLEAdvertisementWatcher, global::Windows.Devices.Bluetooth.Advertisement.BluetoothLEAdvertisementWatcherStoppedEventArgs>>
        {
            public EventState(System.IntPtr obj, int index)
            : base(obj, index)
            {
            }

            protected override global::Windows.Foundation.TypedEventHandler<global::Windows.Devices.Bluetooth.Advertisement.BluetoothLEAdvertisementWatcher, global::Windows.Devices.Bluetooth.Advertisement.BluetoothLEAdvertisementWatcherStoppedEventArgs> GetEventInvoke()
            {
                return (global::Windows.Devices.Bluetooth.Advertisement.BluetoothLEAdvertisementWatcher sender, global::Windows.Devices.Bluetooth.Advertisement.BluetoothLEAdvertisementWatcherStoppedEventArgs args) =>
                {
                    var targetDelegate = TargetDelegate;
                    if (targetDelegate is null)
                    {
                        return ;
                    }
                    targetDelegate.Invoke(sender, args);
                };
            }
        }
    }

    internal sealed unsafe class _EventSource_global__Windows_Foundation_TypedEventHandler_global__Windows_Devices_Enumeration_DeviceWatcher__global__Windows_Devices_Enumeration_DeviceInformation_ : global::ABI.WinRT.Interop.EventSource<global::Windows.Foundation.TypedEventHandler<global::Windows.Devices.Enumeration.DeviceWatcher, global::Windows.Devices.Enumeration.DeviceInformation>>
    {
        private static readonly bool initialized = global::WinRT.GenericTypeInstantiations.Windows_Foundation_TypedEventHandler_2_Windows_Devices_Enumeration_DeviceWatcher__Windows_Devices_Enumeration_DeviceInformation.EnsureInitialized();

        internal _EventSource_global__Windows_Foundation_TypedEventHandler_global__Windows_Devices_Enumeration_DeviceWatcher__global__Windows_Devices_Enumeration_DeviceInformation_(IObjectReference obj,
        delegate* unmanaged[Stdcall]<System.IntPtr, System.IntPtr, WinRT.EventRegistrationToken*, int> addHandler,
        delegate* unmanaged[Stdcall]<System.IntPtr, WinRT.EventRegistrationToken, int> removeHandler, int index) : base(obj, addHandler, removeHandler, index)
        {
            _ = initialized;
        }

        protected override ObjectReferenceValue CreateMarshaler(global::Windows.Foundation.TypedEventHandler<global::Windows.Devices.Enumeration.DeviceWatcher, global::Windows.Devices.Enumeration.DeviceInformation> handler) =>
        global::ABI.Windows.Foundation.TypedEventHandler<global::Windows.Devices.Enumeration.DeviceWatcher, global::Windows.Devices.Enumeration.DeviceInformation>.CreateMarshaler2(handler);

        protected override global::ABI.WinRT.Interop.EventSourceState<global::Windows.Foundation.TypedEventHandler<global::Windows.Devices.Enumeration.DeviceWatcher, global::Windows.Devices.Enumeration.DeviceInformation>> CreateEventSourceState() =>
        new EventState(ObjectReference.ThisPtr, Index);

        [global::WinRT.WinRTExposedType]
        private sealed class EventState : global::ABI.WinRT.Interop.EventSourceState<global::Windows.Foundation.TypedEventHandler<global::Windows.Devices.Enumeration.DeviceWatcher, global::Windows.Devices.Enumeration.DeviceInformation>>
        {
            public EventState(System.IntPtr obj, int index)
            : base(obj, index)
            {
            }

            protected override global::Windows.Foundation.TypedEventHandler<global::Windows.Devices.Enumeration.DeviceWatcher, global::Windows.Devices.Enumeration.DeviceInformation> GetEventInvoke()
            {
                return (global::Windows.Devices.Enumeration.DeviceWatcher sender, global::Windows.Devices.Enumeration.DeviceInformation args) =>
                {
                    var targetDelegate = TargetDelegate;
                    if (targetDelegate is null)
                    {
                        return ;
                    }
                    targetDelegate.Invoke(sender, args);
                };
            }
        }
    }

    internal sealed unsafe class _EventSource_global__Windows_Foundation_TypedEventHandler_global__Windows_Devices_Enumeration_DevicePicker__global__Windows_Devices_Enumeration_DeviceDisconnectButtonClickedEventArgs_ : global::ABI.WinRT.Interop.EventSource<global::Windows.Foundation.TypedEventHandler<global::Windows.Devices.Enumeration.DevicePicker, global::Windows.Devices.Enumeration.DeviceDisconnectButtonClickedEventArgs>>
    {
        private static readonly bool initialized = global::WinRT.GenericTypeInstantiations.Windows_Foundation_TypedEventHandler_2_Windows_Devices_Enumeration_DevicePicker__Windows_Devices_Enumeration_DeviceDisconnectButtonClickedEventArgs.EnsureInitialized();

        internal _EventSource_global__Windows_Foundation_TypedEventHandler_global__Windows_Devices_Enumeration_DevicePicker__global__Windows_Devices_Enumeration_DeviceDisconnectButtonClickedEventArgs_(IObjectReference obj,
        delegate* unmanaged[Stdcall]<System.IntPtr, System.IntPtr, WinRT.EventRegistrationToken*, int> addHandler,
        delegate* unmanaged[Stdcall]<System.IntPtr, WinRT.EventRegistrationToken, int> removeHandler, int index) : base(obj, addHandler, removeHandler, index)
        {
            _ = initialized;
        }

        protected override ObjectReferenceValue CreateMarshaler(global::Windows.Foundation.TypedEventHandler<global::Windows.Devices.Enumeration.DevicePicker, global::Windows.Devices.Enumeration.DeviceDisconnectButtonClickedEventArgs> handler) =>
        global::ABI.Windows.Foundation.TypedEventHandler<global::Windows.Devices.Enumeration.DevicePicker, global::Windows.Devices.Enumeration.DeviceDisconnectButtonClickedEventArgs>.CreateMarshaler2(handler);

        protected override global::ABI.WinRT.Interop.EventSourceState<global::Windows.Foundation.TypedEventHandler<global::Windows.Devices.Enumeration.DevicePicker, global::Windows.Devices.Enumeration.DeviceDisconnectButtonClickedEventArgs>> CreateEventSourceState() =>
        new EventState(ObjectReference.ThisPtr, Index);

        [global::WinRT.WinRTExposedType]
        private sealed class EventState : global::ABI.WinRT.Interop.EventSourceState<global::Windows.Foundation.TypedEventHandler<global::Windows.Devices.Enumeration.DevicePicker, global::Windows.Devices.Enumeration.DeviceDisconnectButtonClickedEventArgs>>
        {
            public EventState(System.IntPtr obj, int index)
            : base(obj, index)
            {
            }

            protected override global::Windows.Foundation.TypedEventHandler<global::Windows.Devices.Enumeration.DevicePicker, global::Windows.Devices.Enumeration.DeviceDisconnectButtonClickedEventArgs> GetEventInvoke()
            {
                return (global::Windows.Devices.Enumeration.DevicePicker sender, global::Windows.Devices.Enumeration.DeviceDisconnectButtonClickedEventArgs args) =>
                {
                    var targetDelegate = TargetDelegate;
                    if (targetDelegate is null)
                    {
                        return ;
                    }
                    targetDelegate.Invoke(sender, args);
                };
            }
        }
    }

    internal sealed unsafe class _EventSource_global__Windows_Foundation_TypedEventHandler_global__Windows_Devices_Enumeration_Pnp_PnpObjectWatcher__object_ : global::ABI.WinRT.Interop.EventSource<global::Windows.Foundation.TypedEventHandler<global::Windows.Devices.Enumeration.Pnp.PnpObjectWatcher, object>>
    {
        private static readonly bool initialized = global::WinRT.GenericTypeInstantiations.Windows_Foundation_TypedEventHandler_2_Windows_Devices_Enumeration_Pnp_PnpObjectWatcher__object.EnsureInitialized();

        internal _EventSource_global__Windows_Foundation_TypedEventHandler_global__Windows_Devices_Enumeration_Pnp_PnpObjectWatcher__object_(IObjectReference obj,
        delegate* unmanaged[Stdcall]<System.IntPtr, System.IntPtr, WinRT.EventRegistrationToken*, int> addHandler,
        delegate* unmanaged[Stdcall]<System.IntPtr, WinRT.EventRegistrationToken, int> removeHandler, int index) : base(obj, addHandler, removeHandler, index)
        {
            _ = initialized;
        }

        protected override ObjectReferenceValue CreateMarshaler(global::Windows.Foundation.TypedEventHandler<global::Windows.Devices.Enumeration.Pnp.PnpObjectWatcher, object> handler) =>
        global::ABI.Windows.Foundation.TypedEventHandler<global::Windows.Devices.Enumeration.Pnp.PnpObjectWatcher, object>.CreateMarshaler2(handler);

        protected override global::ABI.WinRT.Interop.EventSourceState<global::Windows.Foundation.TypedEventHandler<global::Windows.Devices.Enumeration.Pnp.PnpObjectWatcher, object>> CreateEventSourceState() =>
        new EventState(ObjectReference.ThisPtr, Index);

        [global::WinRT.WinRTExposedType]
        private sealed class EventState : global::ABI.WinRT.Interop.EventSourceState<global::Windows.Foundation.TypedEventHandler<global::Windows.Devices.Enumeration.Pnp.PnpObjectWatcher, object>>
        {
            public EventState(System.IntPtr obj, int index)
            : base(obj, index)
            {
            }

            protected override global::Windows.Foundation.TypedEventHandler<global::Windows.Devices.Enumeration.Pnp.PnpObjectWatcher, object> GetEventInvoke()
            {
                return (global::Windows.Devices.Enumeration.Pnp.PnpObjectWatcher sender, object args) =>
                {
                    var targetDelegate = TargetDelegate;
                    if (targetDelegate is null)
                    {
                        return ;
                    }
                    targetDelegate.Invoke(sender, args);
                };
            }
        }
    }

    internal sealed unsafe class _EventSource_global__Windows_Foundation_TypedEventHandler_global__Windows_Devices_Bluetooth_GenericAttributeProfile_GattLocalCharacteristic__global__Windows_Devices_Bluetooth_GenericAttributeProfile_GattWriteRequestedEventArgs_ : global::ABI.WinRT.Interop.EventSource<global::Windows.Foundation.TypedEventHandler<global::Windows.Devices.Bluetooth.GenericAttributeProfile.GattLocalCharacteristic, global::Windows.Devices.Bluetooth.GenericAttributeProfile.GattWriteRequestedEventArgs>>
    {
        private static readonly bool initialized = global::WinRT.GenericTypeInstantiations.Windows_Foundation_TypedEventHandler_2_Windows_Devices_Bluetooth_GenericAttributeProfile_GattLocalCharacteristic__Windows_Devices_Bluetooth_GenericAttributeProfile_GattWriteRequestedEventArgs.EnsureInitialized();

        internal _EventSource_global__Windows_Foundation_TypedEventHandler_global__Windows_Devices_Bluetooth_GenericAttributeProfile_GattLocalCharacteristic__global__Windows_Devices_Bluetooth_GenericAttributeProfile_GattWriteRequestedEventArgs_(IObjectReference obj,
        delegate* unmanaged[Stdcall]<System.IntPtr, System.IntPtr, WinRT.EventRegistrationToken*, int> addHandler,
        delegate* unmanaged[Stdcall]<System.IntPtr, WinRT.EventRegistrationToken, int> removeHandler, int index) : base(obj, addHandler, removeHandler, index)
        {
            _ = initialized;
        }

        protected override ObjectReferenceValue CreateMarshaler(global::Windows.Foundation.TypedEventHandler<global::Windows.Devices.Bluetooth.GenericAttributeProfile.GattLocalCharacteristic, global::Windows.Devices.Bluetooth.GenericAttributeProfile.GattWriteRequestedEventArgs> handler) =>
        global::ABI.Windows.Foundation.TypedEventHandler<global::Windows.Devices.Bluetooth.GenericAttributeProfile.GattLocalCharacteristic, global::Windows.Devices.Bluetooth.GenericAttributeProfile.GattWriteRequestedEventArgs>.CreateMarshaler2(handler);

        protected override global::ABI.WinRT.Interop.EventSourceState<global::Windows.Foundation.TypedEventHandler<global::Windows.Devices.Bluetooth.GenericAttributeProfile.GattLocalCharacteristic, global::Windows.Devices.Bluetooth.GenericAttributeProfile.GattWriteRequestedEventArgs>> CreateEventSourceState() =>
        new EventState(ObjectReference.ThisPtr, Index);

        [global::WinRT.WinRTExposedType]
        private sealed class EventState : global::ABI.WinRT.Interop.EventSourceState<global::Windows.Foundation.TypedEventHandler<global::Windows.Devices.Bluetooth.GenericAttributeProfile.GattLocalCharacteristic, global::Windows.Devices.Bluetooth.GenericAttributeProfile.GattWriteRequestedEventArgs>>
        {
            public EventState(System.IntPtr obj, int index)
            : base(obj, index)
            {
            }

            protected override global::Windows.Foundation.TypedEventHandler<global::Windows.Devices.Bluetooth.GenericAttributeProfile.GattLocalCharacteristic, global::Windows.Devices.Bluetooth.GenericAttributeProfile.GattWriteRequestedEventArgs> GetEventInvoke()
            {
                return (global::Windows.Devices.Bluetooth.GenericAttributeProfile.GattLocalCharacteristic sender, global::Windows.Devices.Bluetooth.GenericAttributeProfile.GattWriteRequestedEventArgs args) =>
                {
                    var targetDelegate = TargetDelegate;
                    if (targetDelegate is null)
                    {
                        return ;
                    }
                    targetDelegate.Invoke(sender, args);
                };
            }
        }
    }

    internal sealed unsafe class _EventSource_global__Windows_Foundation_TypedEventHandler_global__Windows_Devices_Bluetooth_GenericAttributeProfile_GattLocalDescriptor__global__Windows_Devices_Bluetooth_GenericAttributeProfile_GattWriteRequestedEventArgs_ : global::ABI.WinRT.Interop.EventSource<global::Windows.Foundation.TypedEventHandler<global::Windows.Devices.Bluetooth.GenericAttributeProfile.GattLocalDescriptor, global::Windows.Devices.Bluetooth.GenericAttributeProfile.GattWriteRequestedEventArgs>>
    {
        private static readonly bool initialized = global::WinRT.GenericTypeInstantiations.Windows_Foundation_TypedEventHandler_2_Windows_Devices_Bluetooth_GenericAttributeProfile_GattLocalDescriptor__Windows_Devices_Bluetooth_GenericAttributeProfile_GattWriteRequestedEventArgs.EnsureInitialized();

        internal _EventSource_global__Windows_Foundation_TypedEventHandler_global__Windows_Devices_Bluetooth_GenericAttributeProfile_GattLocalDescriptor__global__Windows_Devices_Bluetooth_GenericAttributeProfile_GattWriteRequestedEventArgs_(IObjectReference obj,
        delegate* unmanaged[Stdcall]<System.IntPtr, System.IntPtr, WinRT.EventRegistrationToken*, int> addHandler,
        delegate* unmanaged[Stdcall]<System.IntPtr, WinRT.EventRegistrationToken, int> removeHandler, int index) : base(obj, addHandler, removeHandler, index)
        {
            _ = initialized;
        }

        protected override ObjectReferenceValue CreateMarshaler(global::Windows.Foundation.TypedEventHandler<global::Windows.Devices.Bluetooth.GenericAttributeProfile.GattLocalDescriptor, global::Windows.Devices.Bluetooth.GenericAttributeProfile.GattWriteRequestedEventArgs> handler) =>
        global::ABI.Windows.Foundation.TypedEventHandler<global::Windows.Devices.Bluetooth.GenericAttributeProfile.GattLocalDescriptor, global::Windows.Devices.Bluetooth.GenericAttributeProfile.GattWriteRequestedEventArgs>.CreateMarshaler2(handler);

        protected override global::ABI.WinRT.Interop.EventSourceState<global::Windows.Foundation.TypedEventHandler<global::Windows.Devices.Bluetooth.GenericAttributeProfile.GattLocalDescriptor, global::Windows.Devices.Bluetooth.GenericAttributeProfile.GattWriteRequestedEventArgs>> CreateEventSourceState() =>
        new EventState(ObjectReference.ThisPtr, Index);

        [global::WinRT.WinRTExposedType]
        private sealed class EventState : global::ABI.WinRT.Interop.EventSourceState<global::Windows.Foundation.TypedEventHandler<global::Windows.Devices.Bluetooth.GenericAttributeProfile.GattLocalDescriptor, global::Windows.Devices.Bluetooth.GenericAttributeProfile.GattWriteRequestedEventArgs>>
        {
            public EventState(System.IntPtr obj, int index)
            : base(obj, index)
            {
            }

            protected override global::Windows.Foundation.TypedEventHandler<global::Windows.Devices.Bluetooth.GenericAttributeProfile.GattLocalDescriptor, global::Windows.Devices.Bluetooth.GenericAttributeProfile.GattWriteRequestedEventArgs> GetEventInvoke()
            {
                return (global::Windows.Devices.Bluetooth.GenericAttributeProfile.GattLocalDescriptor sender, global::Windows.Devices.Bluetooth.GenericAttributeProfile.GattWriteRequestedEventArgs args) =>
                {
                    var targetDelegate = TargetDelegate;
                    if (targetDelegate is null)
                    {
                        return ;
                    }
                    targetDelegate.Invoke(sender, args);
                };
            }
        }
    }

    internal sealed unsafe class _EventSource_global__Windows_Foundation_TypedEventHandler_global__Windows_Devices_Enumeration_DeviceInformationCustomPairing__global__Windows_Devices_Enumeration_DevicePairingRequestedEventArgs_ : global::ABI.WinRT.Interop.EventSource<global::Windows.Foundation.TypedEventHandler<global::Windows.Devices.Enumeration.DeviceInformationCustomPairing, global::Windows.Devices.Enumeration.DevicePairingRequestedEventArgs>>
    {
        private static readonly bool initialized = global::WinRT.GenericTypeInstantiations.Windows_Foundation_TypedEventHandler_2_Windows_Devices_Enumeration_DeviceInformationCustomPairing__Windows_Devices_Enumeration_DevicePairingRequestedEventArgs.EnsureInitialized();

        internal _EventSource_global__Windows_Foundation_TypedEventHandler_global__Windows_Devices_Enumeration_DeviceInformationCustomPairing__global__Windows_Devices_Enumeration_DevicePairingRequestedEventArgs_(IObjectReference obj,
        delegate* unmanaged[Stdcall]<System.IntPtr, System.IntPtr, WinRT.EventRegistrationToken*, int> addHandler,
        delegate* unmanaged[Stdcall]<System.IntPtr, WinRT.EventRegistrationToken, int> removeHandler, int index) : base(obj, addHandler, removeHandler, index)
        {
            _ = initialized;
        }

        protected override ObjectReferenceValue CreateMarshaler(global::Windows.Foundation.TypedEventHandler<global::Windows.Devices.Enumeration.DeviceInformationCustomPairing, global::Windows.Devices.Enumeration.DevicePairingRequestedEventArgs> handler) =>
        global::ABI.Windows.Foundation.TypedEventHandler<global::Windows.Devices.Enumeration.DeviceInformationCustomPairing, global::Windows.Devices.Enumeration.DevicePairingRequestedEventArgs>.CreateMarshaler2(handler);

        protected override global::ABI.WinRT.Interop.EventSourceState<global::Windows.Foundation.TypedEventHandler<global::Windows.Devices.Enumeration.DeviceInformationCustomPairing, global::Windows.Devices.Enumeration.DevicePairingRequestedEventArgs>> CreateEventSourceState() =>
        new EventState(ObjectReference.ThisPtr, Index);

        [global::WinRT.WinRTExposedType]
        private sealed class EventState : global::ABI.WinRT.Interop.EventSourceState<global::Windows.Foundation.TypedEventHandler<global::Windows.Devices.Enumeration.DeviceInformationCustomPairing, global::Windows.Devices.Enumeration.DevicePairingRequestedEventArgs>>
        {
            public EventState(System.IntPtr obj, int index)
            : base(obj, index)
            {
            }

            protected override global::Windows.Foundation.TypedEventHandler<global::Windows.Devices.Enumeration.DeviceInformationCustomPairing, global::Windows.Devices.Enumeration.DevicePairingRequestedEventArgs> GetEventInvoke()
            {
                return (global::Windows.Devices.Enumeration.DeviceInformationCustomPairing sender, global::Windows.Devices.Enumeration.DevicePairingRequestedEventArgs args) =>
                {
                    var targetDelegate = TargetDelegate;
                    if (targetDelegate is null)
                    {
                        return ;
                    }
                    targetDelegate.Invoke(sender, args);
                };
            }
        }
    }

    internal sealed unsafe class _EventSource_global__Windows_Foundation_TypedEventHandler_global__Windows_Devices_Enumeration_DevicePicker__global__Windows_Devices_Enumeration_DeviceSelectedEventArgs_ : global::ABI.WinRT.Interop.EventSource<global::Windows.Foundation.TypedEventHandler<global::Windows.Devices.Enumeration.DevicePicker, global::Windows.Devices.Enumeration.DeviceSelectedEventArgs>>
    {
        private static readonly bool initialized = global::WinRT.GenericTypeInstantiations.Windows_Foundation_TypedEventHandler_2_Windows_Devices_Enumeration_DevicePicker__Windows_Devices_Enumeration_DeviceSelectedEventArgs.EnsureInitialized();

        internal _EventSource_global__Windows_Foundation_TypedEventHandler_global__Windows_Devices_Enumeration_DevicePicker__global__Windows_Devices_Enumeration_DeviceSelectedEventArgs_(IObjectReference obj,
        delegate* unmanaged[Stdcall]<System.IntPtr, System.IntPtr, WinRT.EventRegistrationToken*, int> addHandler,
        delegate* unmanaged[Stdcall]<System.IntPtr, WinRT.EventRegistrationToken, int> removeHandler, int index) : base(obj, addHandler, removeHandler, index)
        {
            _ = initialized;
        }

        protected override ObjectReferenceValue CreateMarshaler(global::Windows.Foundation.TypedEventHandler<global::Windows.Devices.Enumeration.DevicePicker, global::Windows.Devices.Enumeration.DeviceSelectedEventArgs> handler) =>
        global::ABI.Windows.Foundation.TypedEventHandler<global::Windows.Devices.Enumeration.DevicePicker, global::Windows.Devices.Enumeration.DeviceSelectedEventArgs>.CreateMarshaler2(handler);

        protected override global::ABI.WinRT.Interop.EventSourceState<global::Windows.Foundation.TypedEventHandler<global::Windows.Devices.Enumeration.DevicePicker, global::Windows.Devices.Enumeration.DeviceSelectedEventArgs>> CreateEventSourceState() =>
        new EventState(ObjectReference.ThisPtr, Index);

        [global::WinRT.WinRTExposedType]
        private sealed class EventState : global::ABI.WinRT.Interop.EventSourceState<global::Windows.Foundation.TypedEventHandler<global::Windows.Devices.Enumeration.DevicePicker, global::Windows.Devices.Enumeration.DeviceSelectedEventArgs>>
        {
            public EventState(System.IntPtr obj, int index)
            : base(obj, index)
            {
            }

            protected override global::Windows.Foundation.TypedEventHandler<global::Windows.Devices.Enumeration.DevicePicker, global::Windows.Devices.Enumeration.DeviceSelectedEventArgs> GetEventInvoke()
            {
                return (global::Windows.Devices.Enumeration.DevicePicker sender, global::Windows.Devices.Enumeration.DeviceSelectedEventArgs args) =>
                {
                    var targetDelegate = TargetDelegate;
                    if (targetDelegate is null)
                    {
                        return ;
                    }
                    targetDelegate.Invoke(sender, args);
                };
            }
        }
    }

    internal sealed unsafe class _EventSource_global__Windows_Foundation_TypedEventHandler_global__Windows_Devices_Bluetooth_Advertisement_BluetoothLEAdvertisementWatcher__global__Windows_Devices_Bluetooth_Advertisement_BluetoothLEAdvertisementReceivedEventArgs_ : global::ABI.WinRT.Interop.EventSource<global::Windows.Foundation.TypedEventHandler<global::Windows.Devices.Bluetooth.Advertisement.BluetoothLEAdvertisementWatcher, global::Windows.Devices.Bluetooth.Advertisement.BluetoothLEAdvertisementReceivedEventArgs>>
    {
        private static readonly bool initialized = global::WinRT.GenericTypeInstantiations.Windows_Foundation_TypedEventHandler_2_Windows_Devices_Bluetooth_Advertisement_BluetoothLEAdvertisementWatcher__Windows_Devices_Bluetooth_Advertisement_BluetoothLEAdvertisementReceivedEventArgs.EnsureInitialized();

        internal _EventSource_global__Windows_Foundation_TypedEventHandler_global__Windows_Devices_Bluetooth_Advertisement_BluetoothLEAdvertisementWatcher__global__Windows_Devices_Bluetooth_Advertisement_BluetoothLEAdvertisementReceivedEventArgs_(IObjectReference obj,
        delegate* unmanaged[Stdcall]<System.IntPtr, System.IntPtr, WinRT.EventRegistrationToken*, int> addHandler,
        delegate* unmanaged[Stdcall]<System.IntPtr, WinRT.EventRegistrationToken, int> removeHandler, int index) : base(obj, addHandler, removeHandler, index)
        {
            _ = initialized;
        }

        protected override ObjectReferenceValue CreateMarshaler(global::Windows.Foundation.TypedEventHandler<global::Windows.Devices.Bluetooth.Advertisement.BluetoothLEAdvertisementWatcher, global::Windows.Devices.Bluetooth.Advertisement.BluetoothLEAdvertisementReceivedEventArgs> handler) =>
        global::ABI.Windows.Foundation.TypedEventHandler<global::Windows.Devices.Bluetooth.Advertisement.BluetoothLEAdvertisementWatcher, global::Windows.Devices.Bluetooth.Advertisement.BluetoothLEAdvertisementReceivedEventArgs>.CreateMarshaler2(handler);

        protected override global::ABI.WinRT.Interop.EventSourceState<global::Windows.Foundation.TypedEventHandler<global::Windows.Devices.Bluetooth.Advertisement.BluetoothLEAdvertisementWatcher, global::Windows.Devices.Bluetooth.Advertisement.BluetoothLEAdvertisementReceivedEventArgs>> CreateEventSourceState() =>
        new EventState(ObjectReference.ThisPtr, Index);

        [global::WinRT.WinRTExposedType]
        private sealed class EventState : global::ABI.WinRT.Interop.EventSourceState<global::Windows.Foundation.TypedEventHandler<global::Windows.Devices.Bluetooth.Advertisement.BluetoothLEAdvertisementWatcher, global::Windows.Devices.Bluetooth.Advertisement.BluetoothLEAdvertisementReceivedEventArgs>>
        {
            public EventState(System.IntPtr obj, int index)
            : base(obj, index)
            {
            }

            protected override global::Windows.Foundation.TypedEventHandler<global::Windows.Devices.Bluetooth.Advertisement.BluetoothLEAdvertisementWatcher, global::Windows.Devices.Bluetooth.Advertisement.BluetoothLEAdvertisementReceivedEventArgs> GetEventInvoke()
            {
                return (global::Windows.Devices.Bluetooth.Advertisement.BluetoothLEAdvertisementWatcher sender, global::Windows.Devices.Bluetooth.Advertisement.BluetoothLEAdvertisementReceivedEventArgs args) =>
                {
                    var targetDelegate = TargetDelegate;
                    if (targetDelegate is null)
                    {
                        return ;
                    }
                    targetDelegate.Invoke(sender, args);
                };
            }
        }
    }

    internal sealed unsafe class _EventSource_global__Windows_Foundation_TypedEventHandler_global__Windows_Devices_Bluetooth_GenericAttributeProfile_GattLocalCharacteristic__object_ : global::ABI.WinRT.Interop.EventSource<global::Windows.Foundation.TypedEventHandler<global::Windows.Devices.Bluetooth.GenericAttributeProfile.GattLocalCharacteristic, object>>
    {
        private static readonly bool initialized = global::WinRT.GenericTypeInstantiations.Windows_Foundation_TypedEventHandler_2_Windows_Devices_Bluetooth_GenericAttributeProfile_GattLocalCharacteristic__object.EnsureInitialized();

        internal _EventSource_global__Windows_Foundation_TypedEventHandler_global__Windows_Devices_Bluetooth_GenericAttributeProfile_GattLocalCharacteristic__object_(IObjectReference obj,
        delegate* unmanaged[Stdcall]<System.IntPtr, System.IntPtr, WinRT.EventRegistrationToken*, int> addHandler,
        delegate* unmanaged[Stdcall]<System.IntPtr, WinRT.EventRegistrationToken, int> removeHandler, int index) : base(obj, addHandler, removeHandler, index)
        {
            _ = initialized;
        }

        protected override ObjectReferenceValue CreateMarshaler(global::Windows.Foundation.TypedEventHandler<global::Windows.Devices.Bluetooth.GenericAttributeProfile.GattLocalCharacteristic, object> handler) =>
        global::ABI.Windows.Foundation.TypedEventHandler<global::Windows.Devices.Bluetooth.GenericAttributeProfile.GattLocalCharacteristic, object>.CreateMarshaler2(handler);

        protected override global::ABI.WinRT.Interop.EventSourceState<global::Windows.Foundation.TypedEventHandler<global::Windows.Devices.Bluetooth.GenericAttributeProfile.GattLocalCharacteristic, object>> CreateEventSourceState() =>
        new EventState(ObjectReference.ThisPtr, Index);

        [global::WinRT.WinRTExposedType]
        private sealed class EventState : global::ABI.WinRT.Interop.EventSourceState<global::Windows.Foundation.TypedEventHandler<global::Windows.Devices.Bluetooth.GenericAttributeProfile.GattLocalCharacteristic, object>>
        {
            public EventState(System.IntPtr obj, int index)
            : base(obj, index)
            {
            }

            protected override global::Windows.Foundation.TypedEventHandler<global::Windows.Devices.Bluetooth.GenericAttributeProfile.GattLocalCharacteristic, object> GetEventInvoke()
            {
                return (global::Windows.Devices.Bluetooth.GenericAttributeProfile.GattLocalCharacteristic sender, object args) =>
                {
                    var targetDelegate = TargetDelegate;
                    if (targetDelegate is null)
                    {
                        return ;
                    }
                    targetDelegate.Invoke(sender, args);
                };
            }
        }
    }

    internal sealed unsafe class _EventSource_global__Windows_Foundation_TypedEventHandler_global__Windows_Devices_Bluetooth_GenericAttributeProfile_GattReadRequest__global__Windows_Devices_Bluetooth_GenericAttributeProfile_GattRequestStateChangedEventArgs_ : global::ABI.WinRT.Interop.EventSource<global::Windows.Foundation.TypedEventHandler<global::Windows.Devices.Bluetooth.GenericAttributeProfile.GattReadRequest, global::Windows.Devices.Bluetooth.GenericAttributeProfile.GattRequestStateChangedEventArgs>>
    {
        private static readonly bool initialized = global::WinRT.GenericTypeInstantiations.Windows_Foundation_TypedEventHandler_2_Windows_Devices_Bluetooth_GenericAttributeProfile_GattReadRequest__Windows_Devices_Bluetooth_GenericAttributeProfile_GattRequestStateChangedEventArgs.EnsureInitialized();

        internal _EventSource_global__Windows_Foundation_TypedEventHandler_global__Windows_Devices_Bluetooth_GenericAttributeProfile_GattReadRequest__global__Windows_Devices_Bluetooth_GenericAttributeProfile_GattRequestStateChangedEventArgs_(IObjectReference obj,
        delegate* unmanaged[Stdcall]<System.IntPtr, System.IntPtr, WinRT.EventRegistrationToken*, int> addHandler,
        delegate* unmanaged[Stdcall]<System.IntPtr, WinRT.EventRegistrationToken, int> removeHandler, int index) : base(obj, addHandler, removeHandler, index)
        {
            _ = initialized;
        }

        protected override ObjectReferenceValue CreateMarshaler(global::Windows.Foundation.TypedEventHandler<global::Windows.Devices.Bluetooth.GenericAttributeProfile.GattReadRequest, global::Windows.Devices.Bluetooth.GenericAttributeProfile.GattRequestStateChangedEventArgs> handler) =>
        global::ABI.Windows.Foundation.TypedEventHandler<global::Windows.Devices.Bluetooth.GenericAttributeProfile.GattReadRequest, global::Windows.Devices.Bluetooth.GenericAttributeProfile.GattRequestStateChangedEventArgs>.CreateMarshaler2(handler);

        protected override global::ABI.WinRT.Interop.EventSourceState<global::Windows.Foundation.TypedEventHandler<global::Windows.Devices.Bluetooth.GenericAttributeProfile.GattReadRequest, global::Windows.Devices.Bluetooth.GenericAttributeProfile.GattRequestStateChangedEventArgs>> CreateEventSourceState() =>
        new EventState(ObjectReference.ThisPtr, Index);

        [global::WinRT.WinRTExposedType]
        private sealed class EventState : global::ABI.WinRT.Interop.EventSourceState<global::Windows.Foundation.TypedEventHandler<global::Windows.Devices.Bluetooth.GenericAttributeProfile.GattReadRequest, global::Windows.Devices.Bluetooth.GenericAttributeProfile.GattRequestStateChangedEventArgs>>
        {
            public EventState(System.IntPtr obj, int index)
            : base(obj, index)
            {
            }

            protected override global::Windows.Foundation.TypedEventHandler<global::Windows.Devices.Bluetooth.GenericAttributeProfile.GattReadRequest, global::Windows.Devices.Bluetooth.GenericAttributeProfile.GattRequestStateChangedEventArgs> GetEventInvoke()
            {
                return (global::Windows.Devices.Bluetooth.GenericAttributeProfile.GattReadRequest sender, global::Windows.Devices.Bluetooth.GenericAttributeProfile.GattRequestStateChangedEventArgs args) =>
                {
                    var targetDelegate = TargetDelegate;
                    if (targetDelegate is null)
                    {
                        return ;
                    }
                    targetDelegate.Invoke(sender, args);
                };
            }
        }
    }

    internal sealed unsafe class _EventSource_global__Windows_Foundation_TypedEventHandler_global__Windows_Devices_Bluetooth_BluetoothDevice__object_ : global::ABI.WinRT.Interop.EventSource<global::Windows.Foundation.TypedEventHandler<global::Windows.Devices.Bluetooth.BluetoothDevice, object>>
    {
        private static readonly bool initialized = global::WinRT.GenericTypeInstantiations.Windows_Foundation_TypedEventHandler_2_Windows_Devices_Bluetooth_BluetoothDevice__object.EnsureInitialized();

        internal _EventSource_global__Windows_Foundation_TypedEventHandler_global__Windows_Devices_Bluetooth_BluetoothDevice__object_(IObjectReference obj,
        delegate* unmanaged[Stdcall]<System.IntPtr, System.IntPtr, WinRT.EventRegistrationToken*, int> addHandler,
        delegate* unmanaged[Stdcall]<System.IntPtr, WinRT.EventRegistrationToken, int> removeHandler, int index) : base(obj, addHandler, removeHandler, index)
        {
            _ = initialized;
        }

        protected override ObjectReferenceValue CreateMarshaler(global::Windows.Foundation.TypedEventHandler<global::Windows.Devices.Bluetooth.BluetoothDevice, object> handler) =>
        global::ABI.Windows.Foundation.TypedEventHandler<global::Windows.Devices.Bluetooth.BluetoothDevice, object>.CreateMarshaler2(handler);

        protected override global::ABI.WinRT.Interop.EventSourceState<global::Windows.Foundation.TypedEventHandler<global::Windows.Devices.Bluetooth.BluetoothDevice, object>> CreateEventSourceState() =>
        new EventState(ObjectReference.ThisPtr, Index);

        [global::WinRT.WinRTExposedType]
        private sealed class EventState : global::ABI.WinRT.Interop.EventSourceState<global::Windows.Foundation.TypedEventHandler<global::Windows.Devices.Bluetooth.BluetoothDevice, object>>
        {
            public EventState(System.IntPtr obj, int index)
            : base(obj, index)
            {
            }

            protected override global::Windows.Foundation.TypedEventHandler<global::Windows.Devices.Bluetooth.BluetoothDevice, object> GetEventInvoke()
            {
                return (global::Windows.Devices.Bluetooth.BluetoothDevice sender, object args) =>
                {
                    var targetDelegate = TargetDelegate;
                    if (targetDelegate is null)
                    {
                        return ;
                    }
                    targetDelegate.Invoke(sender, args);
                };
            }
        }
    }

    internal sealed unsafe class _EventSource_global__Windows_Foundation_TypedEventHandler_global__Windows_Devices_Enumeration_Pnp_PnpObjectWatcher__global__Windows_Devices_Enumeration_Pnp_PnpObject_ : global::ABI.WinRT.Interop.EventSource<global::Windows.Foundation.TypedEventHandler<global::Windows.Devices.Enumeration.Pnp.PnpObjectWatcher, global::Windows.Devices.Enumeration.Pnp.PnpObject>>
    {
        private static readonly bool initialized = global::WinRT.GenericTypeInstantiations.Windows_Foundation_TypedEventHandler_2_Windows_Devices_Enumeration_Pnp_PnpObjectWatcher__Windows_Devices_Enumeration_Pnp_PnpObject.EnsureInitialized();

        internal _EventSource_global__Windows_Foundation_TypedEventHandler_global__Windows_Devices_Enumeration_Pnp_PnpObjectWatcher__global__Windows_Devices_Enumeration_Pnp_PnpObject_(IObjectReference obj,
        delegate* unmanaged[Stdcall]<System.IntPtr, System.IntPtr, WinRT.EventRegistrationToken*, int> addHandler,
        delegate* unmanaged[Stdcall]<System.IntPtr, WinRT.EventRegistrationToken, int> removeHandler, int index) : base(obj, addHandler, removeHandler, index)
        {
            _ = initialized;
        }

        protected override ObjectReferenceValue CreateMarshaler(global::Windows.Foundation.TypedEventHandler<global::Windows.Devices.Enumeration.Pnp.PnpObjectWatcher, global::Windows.Devices.Enumeration.Pnp.PnpObject> handler) =>
        global::ABI.Windows.Foundation.TypedEventHandler<global::Windows.Devices.Enumeration.Pnp.PnpObjectWatcher, global::Windows.Devices.Enumeration.Pnp.PnpObject>.CreateMarshaler2(handler);

        protected override global::ABI.WinRT.Interop.EventSourceState<global::Windows.Foundation.TypedEventHandler<global::Windows.Devices.Enumeration.Pnp.PnpObjectWatcher, global::Windows.Devices.Enumeration.Pnp.PnpObject>> CreateEventSourceState() =>
        new EventState(ObjectReference.ThisPtr, Index);

        [global::WinRT.WinRTExposedType]
        private sealed class EventState : global::ABI.WinRT.Interop.EventSourceState<global::Windows.Foundation.TypedEventHandler<global::Windows.Devices.Enumeration.Pnp.PnpObjectWatcher, global::Windows.Devices.Enumeration.Pnp.PnpObject>>
        {
            public EventState(System.IntPtr obj, int index)
            : base(obj, index)
            {
            }

            protected override global::Windows.Foundation.TypedEventHandler<global::Windows.Devices.Enumeration.Pnp.PnpObjectWatcher, global::Windows.Devices.Enumeration.Pnp.PnpObject> GetEventInvoke()
            {
                return (global::Windows.Devices.Enumeration.Pnp.PnpObjectWatcher sender, global::Windows.Devices.Enumeration.Pnp.PnpObject args) =>
                {
                    var targetDelegate = TargetDelegate;
                    if (targetDelegate is null)
                    {
                        return ;
                    }
                    targetDelegate.Invoke(sender, args);
                };
            }
        }
    }

    internal sealed unsafe class _EventSource_global__Windows_Foundation_TypedEventHandler_global__Windows_Devices_Bluetooth_GenericAttributeProfile_GattServiceProvider__global__Windows_Devices_Bluetooth_GenericAttributeProfile_GattServiceProviderAdvertisementStatusChangedEventArgs_ : global::ABI.WinRT.Interop.EventSource<global::Windows.Foundation.TypedEventHandler<global::Windows.Devices.Bluetooth.GenericAttributeProfile.GattServiceProvider, global::Windows.Devices.Bluetooth.GenericAttributeProfile.GattServiceProviderAdvertisementStatusChangedEventArgs>>
    {
        private static readonly bool initialized = global::WinRT.GenericTypeInstantiations.Windows_Foundation_TypedEventHandler_2_Windows_Devices_Bluetooth_GenericAttributeProfile_GattServiceProvider__Windows_Devices_Bluetooth_GenericAttributeProfile_GattServiceProviderAdvertisementStatusChangedEventArgs.EnsureInitialized();

        internal _EventSource_global__Windows_Foundation_TypedEventHandler_global__Windows_Devices_Bluetooth_GenericAttributeProfile_GattServiceProvider__global__Windows_Devices_Bluetooth_GenericAttributeProfile_GattServiceProviderAdvertisementStatusChangedEventArgs_(IObjectReference obj,
        delegate* unmanaged[Stdcall]<System.IntPtr, System.IntPtr, WinRT.EventRegistrationToken*, int> addHandler,
        delegate* unmanaged[Stdcall]<System.IntPtr, WinRT.EventRegistrationToken, int> removeHandler, int index) : base(obj, addHandler, removeHandler, index)
        {
            _ = initialized;
        }

        protected override ObjectReferenceValue CreateMarshaler(global::Windows.Foundation.TypedEventHandler<global::Windows.Devices.Bluetooth.GenericAttributeProfile.GattServiceProvider, global::Windows.Devices.Bluetooth.GenericAttributeProfile.GattServiceProviderAdvertisementStatusChangedEventArgs> handler) =>
        global::ABI.Windows.Foundation.TypedEventHandler<global::Windows.Devices.Bluetooth.GenericAttributeProfile.GattServiceProvider, global::Windows.Devices.Bluetooth.GenericAttributeProfile.GattServiceProviderAdvertisementStatusChangedEventArgs>.CreateMarshaler2(handler);

        protected override global::ABI.WinRT.Interop.EventSourceState<global::Windows.Foundation.TypedEventHandler<global::Windows.Devices.Bluetooth.GenericAttributeProfile.GattServiceProvider, global::Windows.Devices.Bluetooth.GenericAttributeProfile.GattServiceProviderAdvertisementStatusChangedEventArgs>> CreateEventSourceState() =>
        new EventState(ObjectReference.ThisPtr, Index);

        [global::WinRT.WinRTExposedType]
        private sealed class EventState : global::ABI.WinRT.Interop.EventSourceState<global::Windows.Foundation.TypedEventHandler<global::Windows.Devices.Bluetooth.GenericAttributeProfile.GattServiceProvider, global::Windows.Devices.Bluetooth.GenericAttributeProfile.GattServiceProviderAdvertisementStatusChangedEventArgs>>
        {
            public EventState(System.IntPtr obj, int index)
            : base(obj, index)
            {
            }

            protected override global::Windows.Foundation.TypedEventHandler<global::Windows.Devices.Bluetooth.GenericAttributeProfile.GattServiceProvider, global::Windows.Devices.Bluetooth.GenericAttributeProfile.GattServiceProviderAdvertisementStatusChangedEventArgs> GetEventInvoke()
            {
                return (global::Windows.Devices.Bluetooth.GenericAttributeProfile.GattServiceProvider sender, global::Windows.Devices.Bluetooth.GenericAttributeProfile.GattServiceProviderAdvertisementStatusChangedEventArgs args) =>
                {
                    var targetDelegate = TargetDelegate;
                    if (targetDelegate is null)
                    {
                        return ;
                    }
                    targetDelegate.Invoke(sender, args);
                };
            }
        }
    }

    internal sealed unsafe class _EventSource_global__Windows_Foundation_TypedEventHandler_global__Windows_Devices_Enumeration_Pnp_PnpObjectWatcher__global__Windows_Devices_Enumeration_Pnp_PnpObjectUpdate_ : global::ABI.WinRT.Interop.EventSource<global::Windows.Foundation.TypedEventHandler<global::Windows.Devices.Enumeration.Pnp.PnpObjectWatcher, global::Windows.Devices.Enumeration.Pnp.PnpObjectUpdate>>
    {
        private static readonly bool initialized = global::WinRT.GenericTypeInstantiations.Windows_Foundation_TypedEventHandler_2_Windows_Devices_Enumeration_Pnp_PnpObjectWatcher__Windows_Devices_Enumeration_Pnp_PnpObjectUpdate.EnsureInitialized();

        internal _EventSource_global__Windows_Foundation_TypedEventHandler_global__Windows_Devices_Enumeration_Pnp_PnpObjectWatcher__global__Windows_Devices_Enumeration_Pnp_PnpObjectUpdate_(IObjectReference obj,
        delegate* unmanaged[Stdcall]<System.IntPtr, System.IntPtr, WinRT.EventRegistrationToken*, int> addHandler,
        delegate* unmanaged[Stdcall]<System.IntPtr, WinRT.EventRegistrationToken, int> removeHandler, int index) : base(obj, addHandler, removeHandler, index)
        {
            _ = initialized;
        }

        protected override ObjectReferenceValue CreateMarshaler(global::Windows.Foundation.TypedEventHandler<global::Windows.Devices.Enumeration.Pnp.PnpObjectWatcher, global::Windows.Devices.Enumeration.Pnp.PnpObjectUpdate> handler) =>
        global::ABI.Windows.Foundation.TypedEventHandler<global::Windows.Devices.Enumeration.Pnp.PnpObjectWatcher, global::Windows.Devices.Enumeration.Pnp.PnpObjectUpdate>.CreateMarshaler2(handler);

        protected override global::ABI.WinRT.Interop.EventSourceState<global::Windows.Foundation.TypedEventHandler<global::Windows.Devices.Enumeration.Pnp.PnpObjectWatcher, global::Windows.Devices.Enumeration.Pnp.PnpObjectUpdate>> CreateEventSourceState() =>
        new EventState(ObjectReference.ThisPtr, Index);

        [global::WinRT.WinRTExposedType]
        private sealed class EventState : global::ABI.WinRT.Interop.EventSourceState<global::Windows.Foundation.TypedEventHandler<global::Windows.Devices.Enumeration.Pnp.PnpObjectWatcher, global::Windows.Devices.Enumeration.Pnp.PnpObjectUpdate>>
        {
            public EventState(System.IntPtr obj, int index)
            : base(obj, index)
            {
            }

            protected override global::Windows.Foundation.TypedEventHandler<global::Windows.Devices.Enumeration.Pnp.PnpObjectWatcher, global::Windows.Devices.Enumeration.Pnp.PnpObjectUpdate> GetEventInvoke()
            {
                return (global::Windows.Devices.Enumeration.Pnp.PnpObjectWatcher sender, global::Windows.Devices.Enumeration.Pnp.PnpObjectUpdate args) =>
                {
                    var targetDelegate = TargetDelegate;
                    if (targetDelegate is null)
                    {
                        return ;
                    }
                    targetDelegate.Invoke(sender, args);
                };
            }
        }
    }

    internal sealed unsafe class _EventSource_global__Windows_Foundation_TypedEventHandler_global__Windows_Devices_Bluetooth_GenericAttributeProfile_GattLocalCharacteristic__global__Windows_Devices_Bluetooth_GenericAttributeProfile_GattReadRequestedEventArgs_ : global::ABI.WinRT.Interop.EventSource<global::Windows.Foundation.TypedEventHandler<global::Windows.Devices.Bluetooth.GenericAttributeProfile.GattLocalCharacteristic, global::Windows.Devices.Bluetooth.GenericAttributeProfile.GattReadRequestedEventArgs>>
    {
        private static readonly bool initialized = global::WinRT.GenericTypeInstantiations.Windows_Foundation_TypedEventHandler_2_Windows_Devices_Bluetooth_GenericAttributeProfile_GattLocalCharacteristic__Windows_Devices_Bluetooth_GenericAttributeProfile_GattReadRequestedEventArgs.EnsureInitialized();

        internal _EventSource_global__Windows_Foundation_TypedEventHandler_global__Windows_Devices_Bluetooth_GenericAttributeProfile_GattLocalCharacteristic__global__Windows_Devices_Bluetooth_GenericAttributeProfile_GattReadRequestedEventArgs_(IObjectReference obj,
        delegate* unmanaged[Stdcall]<System.IntPtr, System.IntPtr, WinRT.EventRegistrationToken*, int> addHandler,
        delegate* unmanaged[Stdcall]<System.IntPtr, WinRT.EventRegistrationToken, int> removeHandler, int index) : base(obj, addHandler, removeHandler, index)
        {
            _ = initialized;
        }

        protected override ObjectReferenceValue CreateMarshaler(global::Windows.Foundation.TypedEventHandler<global::Windows.Devices.Bluetooth.GenericAttributeProfile.GattLocalCharacteristic, global::Windows.Devices.Bluetooth.GenericAttributeProfile.GattReadRequestedEventArgs> handler) =>
        global::ABI.Windows.Foundation.TypedEventHandler<global::Windows.Devices.Bluetooth.GenericAttributeProfile.GattLocalCharacteristic, global::Windows.Devices.Bluetooth.GenericAttributeProfile.GattReadRequestedEventArgs>.CreateMarshaler2(handler);

        protected override global::ABI.WinRT.Interop.EventSourceState<global::Windows.Foundation.TypedEventHandler<global::Windows.Devices.Bluetooth.GenericAttributeProfile.GattLocalCharacteristic, global::Windows.Devices.Bluetooth.GenericAttributeProfile.GattReadRequestedEventArgs>> CreateEventSourceState() =>
        new EventState(ObjectReference.ThisPtr, Index);

        [global::WinRT.WinRTExposedType]
        private sealed class EventState : global::ABI.WinRT.Interop.EventSourceState<global::Windows.Foundation.TypedEventHandler<global::Windows.Devices.Bluetooth.GenericAttributeProfile.GattLocalCharacteristic, global::Windows.Devices.Bluetooth.GenericAttributeProfile.GattReadRequestedEventArgs>>
        {
            public EventState(System.IntPtr obj, int index)
            : base(obj, index)
            {
            }

            protected override global::Windows.Foundation.TypedEventHandler<global::Windows.Devices.Bluetooth.GenericAttributeProfile.GattLocalCharacteristic, global::Windows.Devices.Bluetooth.GenericAttributeProfile.GattReadRequestedEventArgs> GetEventInvoke()
            {
                return (global::Windows.Devices.Bluetooth.GenericAttributeProfile.GattLocalCharacteristic sender, global::Windows.Devices.Bluetooth.GenericAttributeProfile.GattReadRequestedEventArgs args) =>
                {
                    var targetDelegate = TargetDelegate;
                    if (targetDelegate is null)
                    {
                        return ;
                    }
                    targetDelegate.Invoke(sender, args);
                };
            }
        }
    }

    internal sealed unsafe class _EventSource_global__Windows_Foundation_TypedEventHandler_global__Windows_Devices_Bluetooth_GenericAttributeProfile_GattLocalDescriptor__global__Windows_Devices_Bluetooth_GenericAttributeProfile_GattReadRequestedEventArgs_ : global::ABI.WinRT.Interop.EventSource<global::Windows.Foundation.TypedEventHandler<global::Windows.Devices.Bluetooth.GenericAttributeProfile.GattLocalDescriptor, global::Windows.Devices.Bluetooth.GenericAttributeProfile.GattReadRequestedEventArgs>>
    {
        private static readonly bool initialized = global::WinRT.GenericTypeInstantiations.Windows_Foundation_TypedEventHandler_2_Windows_Devices_Bluetooth_GenericAttributeProfile_GattLocalDescriptor__Windows_Devices_Bluetooth_GenericAttributeProfile_GattReadRequestedEventArgs.EnsureInitialized();

        internal _EventSource_global__Windows_Foundation_TypedEventHandler_global__Windows_Devices_Bluetooth_GenericAttributeProfile_GattLocalDescriptor__global__Windows_Devices_Bluetooth_GenericAttributeProfile_GattReadRequestedEventArgs_(IObjectReference obj,
        delegate* unmanaged[Stdcall]<System.IntPtr, System.IntPtr, WinRT.EventRegistrationToken*, int> addHandler,
        delegate* unmanaged[Stdcall]<System.IntPtr, WinRT.EventRegistrationToken, int> removeHandler, int index) : base(obj, addHandler, removeHandler, index)
        {
            _ = initialized;
        }

        protected override ObjectReferenceValue CreateMarshaler(global::Windows.Foundation.TypedEventHandler<global::Windows.Devices.Bluetooth.GenericAttributeProfile.GattLocalDescriptor, global::Windows.Devices.Bluetooth.GenericAttributeProfile.GattReadRequestedEventArgs> handler) =>
        global::ABI.Windows.Foundation.TypedEventHandler<global::Windows.Devices.Bluetooth.GenericAttributeProfile.GattLocalDescriptor, global::Windows.Devices.Bluetooth.GenericAttributeProfile.GattReadRequestedEventArgs>.CreateMarshaler2(handler);

        protected override global::ABI.WinRT.Interop.EventSourceState<global::Windows.Foundation.TypedEventHandler<global::Windows.Devices.Bluetooth.GenericAttributeProfile.GattLocalDescriptor, global::Windows.Devices.Bluetooth.GenericAttributeProfile.GattReadRequestedEventArgs>> CreateEventSourceState() =>
        new EventState(ObjectReference.ThisPtr, Index);

        [global::WinRT.WinRTExposedType]
        private sealed class EventState : global::ABI.WinRT.Interop.EventSourceState<global::Windows.Foundation.TypedEventHandler<global::Windows.Devices.Bluetooth.GenericAttributeProfile.GattLocalDescriptor, global::Windows.Devices.Bluetooth.GenericAttributeProfile.GattReadRequestedEventArgs>>
        {
            public EventState(System.IntPtr obj, int index)
            : base(obj, index)
            {
            }

            protected override global::Windows.Foundation.TypedEventHandler<global::Windows.Devices.Bluetooth.GenericAttributeProfile.GattLocalDescriptor, global::Windows.Devices.Bluetooth.GenericAttributeProfile.GattReadRequestedEventArgs> GetEventInvoke()
            {
                return (global::Windows.Devices.Bluetooth.GenericAttributeProfile.GattLocalDescriptor sender, global::Windows.Devices.Bluetooth.GenericAttributeProfile.GattReadRequestedEventArgs args) =>
                {
                    var targetDelegate = TargetDelegate;
                    if (targetDelegate is null)
                    {
                        return ;
                    }
                    targetDelegate.Invoke(sender, args);
                };
            }
        }
    }

    internal sealed unsafe class _EventSource_global__Windows_Foundation_TypedEventHandler_global__Windows_Devices_Bluetooth_GenericAttributeProfile_GattSession__global__Windows_Devices_Bluetooth_GenericAttributeProfile_GattSessionStatusChangedEventArgs_ : global::ABI.WinRT.Interop.EventSource<global::Windows.Foundation.TypedEventHandler<global::Windows.Devices.Bluetooth.GenericAttributeProfile.GattSession, global::Windows.Devices.Bluetooth.GenericAttributeProfile.GattSessionStatusChangedEventArgs>>
    {
        private static readonly bool initialized = global::WinRT.GenericTypeInstantiations.Windows_Foundation_TypedEventHandler_2_Windows_Devices_Bluetooth_GenericAttributeProfile_GattSession__Windows_Devices_Bluetooth_GenericAttributeProfile_GattSessionStatusChangedEventArgs.EnsureInitialized();

        internal _EventSource_global__Windows_Foundation_TypedEventHandler_global__Windows_Devices_Bluetooth_GenericAttributeProfile_GattSession__global__Windows_Devices_Bluetooth_GenericAttributeProfile_GattSessionStatusChangedEventArgs_(IObjectReference obj,
        delegate* unmanaged[Stdcall]<System.IntPtr, System.IntPtr, WinRT.EventRegistrationToken*, int> addHandler,
        delegate* unmanaged[Stdcall]<System.IntPtr, WinRT.EventRegistrationToken, int> removeHandler, int index) : base(obj, addHandler, removeHandler, index)
        {
            _ = initialized;
        }

        protected override ObjectReferenceValue CreateMarshaler(global::Windows.Foundation.TypedEventHandler<global::Windows.Devices.Bluetooth.GenericAttributeProfile.GattSession, global::Windows.Devices.Bluetooth.GenericAttributeProfile.GattSessionStatusChangedEventArgs> handler) =>
        global::ABI.Windows.Foundation.TypedEventHandler<global::Windows.Devices.Bluetooth.GenericAttributeProfile.GattSession, global::Windows.Devices.Bluetooth.GenericAttributeProfile.GattSessionStatusChangedEventArgs>.CreateMarshaler2(handler);

        protected override global::ABI.WinRT.Interop.EventSourceState<global::Windows.Foundation.TypedEventHandler<global::Windows.Devices.Bluetooth.GenericAttributeProfile.GattSession, global::Windows.Devices.Bluetooth.GenericAttributeProfile.GattSessionStatusChangedEventArgs>> CreateEventSourceState() =>
        new EventState(ObjectReference.ThisPtr, Index);

        [global::WinRT.WinRTExposedType]
        private sealed class EventState : global::ABI.WinRT.Interop.EventSourceState<global::Windows.Foundation.TypedEventHandler<global::Windows.Devices.Bluetooth.GenericAttributeProfile.GattSession, global::Windows.Devices.Bluetooth.GenericAttributeProfile.GattSessionStatusChangedEventArgs>>
        {
            public EventState(System.IntPtr obj, int index)
            : base(obj, index)
            {
            }

            protected override global::Windows.Foundation.TypedEventHandler<global::Windows.Devices.Bluetooth.GenericAttributeProfile.GattSession, global::Windows.Devices.Bluetooth.GenericAttributeProfile.GattSessionStatusChangedEventArgs> GetEventInvoke()
            {
                return (global::Windows.Devices.Bluetooth.GenericAttributeProfile.GattSession sender, global::Windows.Devices.Bluetooth.GenericAttributeProfile.GattSessionStatusChangedEventArgs args) =>
                {
                    var targetDelegate = TargetDelegate;
                    if (targetDelegate is null)
                    {
                        return ;
                    }
                    targetDelegate.Invoke(sender, args);
                };
            }
        }
    }

    internal sealed unsafe class _EventSource_global__Windows_Foundation_TypedEventHandler_global__Windows_Devices_Enumeration_DevicePicker__object_ : global::ABI.WinRT.Interop.EventSource<global::Windows.Foundation.TypedEventHandler<global::Windows.Devices.Enumeration.DevicePicker, object>>
    {
        private static readonly bool initialized = global::WinRT.GenericTypeInstantiations.Windows_Foundation_TypedEventHandler_2_Windows_Devices_Enumeration_DevicePicker__object.EnsureInitialized();

        internal _EventSource_global__Windows_Foundation_TypedEventHandler_global__Windows_Devices_Enumeration_DevicePicker__object_(IObjectReference obj,
        delegate* unmanaged[Stdcall]<System.IntPtr, System.IntPtr, WinRT.EventRegistrationToken*, int> addHandler,
        delegate* unmanaged[Stdcall]<System.IntPtr, WinRT.EventRegistrationToken, int> removeHandler, int index) : base(obj, addHandler, removeHandler, index)
        {
            _ = initialized;
        }

        protected override ObjectReferenceValue CreateMarshaler(global::Windows.Foundation.TypedEventHandler<global::Windows.Devices.Enumeration.DevicePicker, object> handler) =>
        global::ABI.Windows.Foundation.TypedEventHandler<global::Windows.Devices.Enumeration.DevicePicker, object>.CreateMarshaler2(handler);

        protected override global::ABI.WinRT.Interop.EventSourceState<global::Windows.Foundation.TypedEventHandler<global::Windows.Devices.Enumeration.DevicePicker, object>> CreateEventSourceState() =>
        new EventState(ObjectReference.ThisPtr, Index);

        [global::WinRT.WinRTExposedType]
        private sealed class EventState : global::ABI.WinRT.Interop.EventSourceState<global::Windows.Foundation.TypedEventHandler<global::Windows.Devices.Enumeration.DevicePicker, object>>
        {
            public EventState(System.IntPtr obj, int index)
            : base(obj, index)
            {
            }

            protected override global::Windows.Foundation.TypedEventHandler<global::Windows.Devices.Enumeration.DevicePicker, object> GetEventInvoke()
            {
                return (global::Windows.Devices.Enumeration.DevicePicker sender, object args) =>
                {
                    var targetDelegate = TargetDelegate;
                    if (targetDelegate is null)
                    {
                        return ;
                    }
                    targetDelegate.Invoke(sender, args);
                };
            }
        }
    }

    internal sealed unsafe class _EventSource_global__Windows_Foundation_TypedEventHandler_global__Windows_Devices_Bluetooth_BluetoothLEDevice__object_ : global::ABI.WinRT.Interop.EventSource<global::Windows.Foundation.TypedEventHandler<global::Windows.Devices.Bluetooth.BluetoothLEDevice, object>>
    {
        private static readonly bool initialized = global::WinRT.GenericTypeInstantiations.Windows_Foundation_TypedEventHandler_2_Windows_Devices_Bluetooth_BluetoothLEDevice__object.EnsureInitialized();

        internal _EventSource_global__Windows_Foundation_TypedEventHandler_global__Windows_Devices_Bluetooth_BluetoothLEDevice__object_(IObjectReference obj,
        delegate* unmanaged[Stdcall]<System.IntPtr, System.IntPtr, WinRT.EventRegistrationToken*, int> addHandler,
        delegate* unmanaged[Stdcall]<System.IntPtr, WinRT.EventRegistrationToken, int> removeHandler, int index) : base(obj, addHandler, removeHandler, index)
        {
            _ = initialized;
        }

        protected override ObjectReferenceValue CreateMarshaler(global::Windows.Foundation.TypedEventHandler<global::Windows.Devices.Bluetooth.BluetoothLEDevice, object> handler) =>
        global::ABI.Windows.Foundation.TypedEventHandler<global::Windows.Devices.Bluetooth.BluetoothLEDevice, object>.CreateMarshaler2(handler);

        protected override global::ABI.WinRT.Interop.EventSourceState<global::Windows.Foundation.TypedEventHandler<global::Windows.Devices.Bluetooth.BluetoothLEDevice, object>> CreateEventSourceState() =>
        new EventState(ObjectReference.ThisPtr, Index);

        [global::WinRT.WinRTExposedType]
        private sealed class EventState : global::ABI.WinRT.Interop.EventSourceState<global::Windows.Foundation.TypedEventHandler<global::Windows.Devices.Bluetooth.BluetoothLEDevice, object>>
        {
            public EventState(System.IntPtr obj, int index)
            : base(obj, index)
            {
            }

            protected override global::Windows.Foundation.TypedEventHandler<global::Windows.Devices.Bluetooth.BluetoothLEDevice, object> GetEventInvoke()
            {
                return (global::Windows.Devices.Bluetooth.BluetoothLEDevice sender, object args) =>
                {
                    var targetDelegate = TargetDelegate;
                    if (targetDelegate is null)
                    {
                        return ;
                    }
                    targetDelegate.Invoke(sender, args);
                };
            }
        }
    }

    internal sealed unsafe class _EventSource_global__Windows_Foundation_TypedEventHandler_global__Windows_Devices_Enumeration_DeviceWatcher__object_ : global::ABI.WinRT.Interop.EventSource<global::Windows.Foundation.TypedEventHandler<global::Windows.Devices.Enumeration.DeviceWatcher, object>>
    {
        private static readonly bool initialized = global::WinRT.GenericTypeInstantiations.Windows_Foundation_TypedEventHandler_2_Windows_Devices_Enumeration_DeviceWatcher__object.EnsureInitialized();

        internal _EventSource_global__Windows_Foundation_TypedEventHandler_global__Windows_Devices_Enumeration_DeviceWatcher__object_(IObjectReference obj,
        delegate* unmanaged[Stdcall]<System.IntPtr, System.IntPtr, WinRT.EventRegistrationToken*, int> addHandler,
        delegate* unmanaged[Stdcall]<System.IntPtr, WinRT.EventRegistrationToken, int> removeHandler, int index) : base(obj, addHandler, removeHandler, index)
        {
            _ = initialized;
        }

        protected override ObjectReferenceValue CreateMarshaler(global::Windows.Foundation.TypedEventHandler<global::Windows.Devices.Enumeration.DeviceWatcher, object> handler) =>
        global::ABI.Windows.Foundation.TypedEventHandler<global::Windows.Devices.Enumeration.DeviceWatcher, object>.CreateMarshaler2(handler);

        protected override global::ABI.WinRT.Interop.EventSourceState<global::Windows.Foundation.TypedEventHandler<global::Windows.Devices.Enumeration.DeviceWatcher, object>> CreateEventSourceState() =>
        new EventState(ObjectReference.ThisPtr, Index);

        [global::WinRT.WinRTExposedType]
        private sealed class EventState : global::ABI.WinRT.Interop.EventSourceState<global::Windows.Foundation.TypedEventHandler<global::Windows.Devices.Enumeration.DeviceWatcher, object>>
        {
            public EventState(System.IntPtr obj, int index)
            : base(obj, index)
            {
            }

            protected override global::Windows.Foundation.TypedEventHandler<global::Windows.Devices.Enumeration.DeviceWatcher, object> GetEventInvoke()
            {
                return (global::Windows.Devices.Enumeration.DeviceWatcher sender, object args) =>
                {
                    var targetDelegate = TargetDelegate;
                    if (targetDelegate is null)
                    {
                        return ;
                    }
                    targetDelegate.Invoke(sender, args);
                };
            }
        }
    }

    internal sealed unsafe class _EventSource_global__Windows_Foundation_TypedEventHandler_global__Windows_Devices_Bluetooth_GenericAttributeProfile_GattSubscribedClient__object_ : global::ABI.WinRT.Interop.EventSource<global::Windows.Foundation.TypedEventHandler<global::Windows.Devices.Bluetooth.GenericAttributeProfile.GattSubscribedClient, object>>
    {
        private static readonly bool initialized = global::WinRT.GenericTypeInstantiations.Windows_Foundation_TypedEventHandler_2_Windows_Devices_Bluetooth_GenericAttributeProfile_GattSubscribedClient__object.EnsureInitialized();

        internal _EventSource_global__Windows_Foundation_TypedEventHandler_global__Windows_Devices_Bluetooth_GenericAttributeProfile_GattSubscribedClient__object_(IObjectReference obj,
        delegate* unmanaged[Stdcall]<System.IntPtr, System.IntPtr, WinRT.EventRegistrationToken*, int> addHandler,
        delegate* unmanaged[Stdcall]<System.IntPtr, WinRT.EventRegistrationToken, int> removeHandler, int index) : base(obj, addHandler, removeHandler, index)
        {
            _ = initialized;
        }

        protected override ObjectReferenceValue CreateMarshaler(global::Windows.Foundation.TypedEventHandler<global::Windows.Devices.Bluetooth.GenericAttributeProfile.GattSubscribedClient, object> handler) =>
        global::ABI.Windows.Foundation.TypedEventHandler<global::Windows.Devices.Bluetooth.GenericAttributeProfile.GattSubscribedClient, object>.CreateMarshaler2(handler);

        protected override global::ABI.WinRT.Interop.EventSourceState<global::Windows.Foundation.TypedEventHandler<global::Windows.Devices.Bluetooth.GenericAttributeProfile.GattSubscribedClient, object>> CreateEventSourceState() =>
        new EventState(ObjectReference.ThisPtr, Index);

        [global::WinRT.WinRTExposedType]
        private sealed class EventState : global::ABI.WinRT.Interop.EventSourceState<global::Windows.Foundation.TypedEventHandler<global::Windows.Devices.Bluetooth.GenericAttributeProfile.GattSubscribedClient, object>>
        {
            public EventState(System.IntPtr obj, int index)
            : base(obj, index)
            {
            }

            protected override global::Windows.Foundation.TypedEventHandler<global::Windows.Devices.Bluetooth.GenericAttributeProfile.GattSubscribedClient, object> GetEventInvoke()
            {
                return (global::Windows.Devices.Bluetooth.GenericAttributeProfile.GattSubscribedClient sender, object args) =>
                {
                    var targetDelegate = TargetDelegate;
                    if (targetDelegate is null)
                    {
                        return ;
                    }
                    targetDelegate.Invoke(sender, args);
                };
            }
        }
    }

    internal sealed unsafe class _EventSource_global__Windows_Foundation_TypedEventHandler_global__Windows_Devices_Enumeration_DeviceWatcher__global__Windows_Devices_Enumeration_DeviceInformationUpdate_ : global::ABI.WinRT.Interop.EventSource<global::Windows.Foundation.TypedEventHandler<global::Windows.Devices.Enumeration.DeviceWatcher, global::Windows.Devices.Enumeration.DeviceInformationUpdate>>
    {
        private static readonly bool initialized = global::WinRT.GenericTypeInstantiations.Windows_Foundation_TypedEventHandler_2_Windows_Devices_Enumeration_DeviceWatcher__Windows_Devices_Enumeration_DeviceInformationUpdate.EnsureInitialized();

        internal _EventSource_global__Windows_Foundation_TypedEventHandler_global__Windows_Devices_Enumeration_DeviceWatcher__global__Windows_Devices_Enumeration_DeviceInformationUpdate_(IObjectReference obj,
        delegate* unmanaged[Stdcall]<System.IntPtr, System.IntPtr, WinRT.EventRegistrationToken*, int> addHandler,
        delegate* unmanaged[Stdcall]<System.IntPtr, WinRT.EventRegistrationToken, int> removeHandler, int index) : base(obj, addHandler, removeHandler, index)
        {
            _ = initialized;
        }

        protected override ObjectReferenceValue CreateMarshaler(global::Windows.Foundation.TypedEventHandler<global::Windows.Devices.Enumeration.DeviceWatcher, global::Windows.Devices.Enumeration.DeviceInformationUpdate> handler) =>
        global::ABI.Windows.Foundation.TypedEventHandler<global::Windows.Devices.Enumeration.DeviceWatcher, global::Windows.Devices.Enumeration.DeviceInformationUpdate>.CreateMarshaler2(handler);

        protected override global::ABI.WinRT.Interop.EventSourceState<global::Windows.Foundation.TypedEventHandler<global::Windows.Devices.Enumeration.DeviceWatcher, global::Windows.Devices.Enumeration.DeviceInformationUpdate>> CreateEventSourceState() =>
        new EventState(ObjectReference.ThisPtr, Index);

        [global::WinRT.WinRTExposedType]
        private sealed class EventState : global::ABI.WinRT.Interop.EventSourceState<global::Windows.Foundation.TypedEventHandler<global::Windows.Devices.Enumeration.DeviceWatcher, global::Windows.Devices.Enumeration.DeviceInformationUpdate>>
        {
            public EventState(System.IntPtr obj, int index)
            : base(obj, index)
            {
            }

            protected override global::Windows.Foundation.TypedEventHandler<global::Windows.Devices.Enumeration.DeviceWatcher, global::Windows.Devices.Enumeration.DeviceInformationUpdate> GetEventInvoke()
            {
                return (global::Windows.Devices.Enumeration.DeviceWatcher sender, global::Windows.Devices.Enumeration.DeviceInformationUpdate args) =>
                {
                    var targetDelegate = TargetDelegate;
                    if (targetDelegate is null)
                    {
                        return ;
                    }
                    targetDelegate.Invoke(sender, args);
                };
            }
        }
    }

    internal sealed unsafe class _EventSource_global__Windows_Foundation_TypedEventHandler_global__Windows_Devices_Enumeration_DeviceAccessInformation__global__Windows_Devices_Enumeration_DeviceAccessChangedEventArgs_ : global::ABI.WinRT.Interop.EventSource<global::Windows.Foundation.TypedEventHandler<global::Windows.Devices.Enumeration.DeviceAccessInformation, global::Windows.Devices.Enumeration.DeviceAccessChangedEventArgs>>
    {
        private static readonly bool initialized = global::WinRT.GenericTypeInstantiations.Windows_Foundation_TypedEventHandler_2_Windows_Devices_Enumeration_DeviceAccessInformation__Windows_Devices_Enumeration_DeviceAccessChangedEventArgs.EnsureInitialized();

        internal _EventSource_global__Windows_Foundation_TypedEventHandler_global__Windows_Devices_Enumeration_DeviceAccessInformation__global__Windows_Devices_Enumeration_DeviceAccessChangedEventArgs_(IObjectReference obj,
        delegate* unmanaged[Stdcall]<System.IntPtr, System.IntPtr, WinRT.EventRegistrationToken*, int> addHandler,
        delegate* unmanaged[Stdcall]<System.IntPtr, WinRT.EventRegistrationToken, int> removeHandler, int index) : base(obj, addHandler, removeHandler, index)
        {
            _ = initialized;
        }

        protected override ObjectReferenceValue CreateMarshaler(global::Windows.Foundation.TypedEventHandler<global::Windows.Devices.Enumeration.DeviceAccessInformation, global::Windows.Devices.Enumeration.DeviceAccessChangedEventArgs> handler) =>
        global::ABI.Windows.Foundation.TypedEventHandler<global::Windows.Devices.Enumeration.DeviceAccessInformation, global::Windows.Devices.Enumeration.DeviceAccessChangedEventArgs>.CreateMarshaler2(handler);

        protected override global::ABI.WinRT.Interop.EventSourceState<global::Windows.Foundation.TypedEventHandler<global::Windows.Devices.Enumeration.DeviceAccessInformation, global::Windows.Devices.Enumeration.DeviceAccessChangedEventArgs>> CreateEventSourceState() =>
        new EventState(ObjectReference.ThisPtr, Index);

        [global::WinRT.WinRTExposedType]
        private sealed class EventState : global::ABI.WinRT.Interop.EventSourceState<global::Windows.Foundation.TypedEventHandler<global::Windows.Devices.Enumeration.DeviceAccessInformation, global::Windows.Devices.Enumeration.DeviceAccessChangedEventArgs>>
        {
            public EventState(System.IntPtr obj, int index)
            : base(obj, index)
            {
            }

            protected override global::Windows.Foundation.TypedEventHandler<global::Windows.Devices.Enumeration.DeviceAccessInformation, global::Windows.Devices.Enumeration.DeviceAccessChangedEventArgs> GetEventInvoke()
            {
                return (global::Windows.Devices.Enumeration.DeviceAccessInformation sender, global::Windows.Devices.Enumeration.DeviceAccessChangedEventArgs args) =>
                {
                    var targetDelegate = TargetDelegate;
                    if (targetDelegate is null)
                    {
                        return ;
                    }
                    targetDelegate.Invoke(sender, args);
                };
            }
        }
    }

    internal sealed unsafe class _EventSource_global__Windows_Foundation_TypedEventHandler_global__Windows_Devices_Enumeration_DeviceInformationCustomPairing__global__Windows_Devices_Enumeration_DevicePairingSetMembersRequestedEventArgs_ : global::ABI.WinRT.Interop.EventSource<global::Windows.Foundation.TypedEventHandler<global::Windows.Devices.Enumeration.DeviceInformationCustomPairing, global::Windows.Devices.Enumeration.DevicePairingSetMembersRequestedEventArgs>>
    {
        private static readonly bool initialized = global::WinRT.GenericTypeInstantiations.Windows_Foundation_TypedEventHandler_2_Windows_Devices_Enumeration_DeviceInformationCustomPairing__Windows_Devices_Enumeration_DevicePairingSetMembersRequestedEventArgs.EnsureInitialized();

        internal _EventSource_global__Windows_Foundation_TypedEventHandler_global__Windows_Devices_Enumeration_DeviceInformationCustomPairing__global__Windows_Devices_Enumeration_DevicePairingSetMembersRequestedEventArgs_(IObjectReference obj,
        delegate* unmanaged[Stdcall]<System.IntPtr, System.IntPtr, WinRT.EventRegistrationToken*, int> addHandler,
        delegate* unmanaged[Stdcall]<System.IntPtr, WinRT.EventRegistrationToken, int> removeHandler, int index) : base(obj, addHandler, removeHandler, index)
        {
            _ = initialized;
        }

        protected override ObjectReferenceValue CreateMarshaler(global::Windows.Foundation.TypedEventHandler<global::Windows.Devices.Enumeration.DeviceInformationCustomPairing, global::Windows.Devices.Enumeration.DevicePairingSetMembersRequestedEventArgs> handler) =>
        global::ABI.Windows.Foundation.TypedEventHandler<global::Windows.Devices.Enumeration.DeviceInformationCustomPairing, global::Windows.Devices.Enumeration.DevicePairingSetMembersRequestedEventArgs>.CreateMarshaler2(handler);

        protected override global::ABI.WinRT.Interop.EventSourceState<global::Windows.Foundation.TypedEventHandler<global::Windows.Devices.Enumeration.DeviceInformationCustomPairing, global::Windows.Devices.Enumeration.DevicePairingSetMembersRequestedEventArgs>> CreateEventSourceState() =>
        new EventState(ObjectReference.ThisPtr, Index);

        [global::WinRT.WinRTExposedType]
        private sealed class EventState : global::ABI.WinRT.Interop.EventSourceState<global::Windows.Foundation.TypedEventHandler<global::Windows.Devices.Enumeration.DeviceInformationCustomPairing, global::Windows.Devices.Enumeration.DevicePairingSetMembersRequestedEventArgs>>
        {
            public EventState(System.IntPtr obj, int index)
            : base(obj, index)
            {
            }

            protected override global::Windows.Foundation.TypedEventHandler<global::Windows.Devices.Enumeration.DeviceInformationCustomPairing, global::Windows.Devices.Enumeration.DevicePairingSetMembersRequestedEventArgs> GetEventInvoke()
            {
                return (global::Windows.Devices.Enumeration.DeviceInformationCustomPairing sender, global::Windows.Devices.Enumeration.DevicePairingSetMembersRequestedEventArgs args) =>
                {
                    var targetDelegate = TargetDelegate;
                    if (targetDelegate is null)
                    {
                        return ;
                    }
                    targetDelegate.Invoke(sender, args);
                };
            }
        }
    }

    internal sealed unsafe class _EventSource_global__Windows_Foundation_TypedEventHandler_global__Windows_Devices_Bluetooth_GenericAttributeProfile_GattCharacteristic__global__Windows_Devices_Bluetooth_GenericAttributeProfile_GattValueChangedEventArgs_ : global::ABI.WinRT.Interop.EventSource<global::Windows.Foundation.TypedEventHandler<global::Windows.Devices.Bluetooth.GenericAttributeProfile.GattCharacteristic, global::Windows.Devices.Bluetooth.GenericAttributeProfile.GattValueChangedEventArgs>>
    {
        private static readonly bool initialized = global::WinRT.GenericTypeInstantiations.Windows_Foundation_TypedEventHandler_2_Windows_Devices_Bluetooth_GenericAttributeProfile_GattCharacteristic__Windows_Devices_Bluetooth_GenericAttributeProfile_GattValueChangedEventArgs.EnsureInitialized();

        internal _EventSource_global__Windows_Foundation_TypedEventHandler_global__Windows_Devices_Bluetooth_GenericAttributeProfile_GattCharacteristic__global__Windows_Devices_Bluetooth_GenericAttributeProfile_GattValueChangedEventArgs_(IObjectReference obj,
        delegate* unmanaged[Stdcall]<System.IntPtr, System.IntPtr, WinRT.EventRegistrationToken*, int> addHandler,
        delegate* unmanaged[Stdcall]<System.IntPtr, WinRT.EventRegistrationToken, int> removeHandler, int index) : base(obj, addHandler, removeHandler, index)
        {
            _ = initialized;
        }

        protected override ObjectReferenceValue CreateMarshaler(global::Windows.Foundation.TypedEventHandler<global::Windows.Devices.Bluetooth.GenericAttributeProfile.GattCharacteristic, global::Windows.Devices.Bluetooth.GenericAttributeProfile.GattValueChangedEventArgs> handler) =>
        global::ABI.Windows.Foundation.TypedEventHandler<global::Windows.Devices.Bluetooth.GenericAttributeProfile.GattCharacteristic, global::Windows.Devices.Bluetooth.GenericAttributeProfile.GattValueChangedEventArgs>.CreateMarshaler2(handler);

        protected override global::ABI.WinRT.Interop.EventSourceState<global::Windows.Foundation.TypedEventHandler<global::Windows.Devices.Bluetooth.GenericAttributeProfile.GattCharacteristic, global::Windows.Devices.Bluetooth.GenericAttributeProfile.GattValueChangedEventArgs>> CreateEventSourceState() =>
        new EventState(ObjectReference.ThisPtr, Index);

        [global::WinRT.WinRTExposedType]
        private sealed class EventState : global::ABI.WinRT.Interop.EventSourceState<global::Windows.Foundation.TypedEventHandler<global::Windows.Devices.Bluetooth.GenericAttributeProfile.GattCharacteristic, global::Windows.Devices.Bluetooth.GenericAttributeProfile.GattValueChangedEventArgs>>
        {
            public EventState(System.IntPtr obj, int index)
            : base(obj, index)
            {
            }

            protected override global::Windows.Foundation.TypedEventHandler<global::Windows.Devices.Bluetooth.GenericAttributeProfile.GattCharacteristic, global::Windows.Devices.Bluetooth.GenericAttributeProfile.GattValueChangedEventArgs> GetEventInvoke()
            {
                return (global::Windows.Devices.Bluetooth.GenericAttributeProfile.GattCharacteristic sender, global::Windows.Devices.Bluetooth.GenericAttributeProfile.GattValueChangedEventArgs args) =>
                {
                    var targetDelegate = TargetDelegate;
                    if (targetDelegate is null)
                    {
                        return ;
                    }
                    targetDelegate.Invoke(sender, args);
                };
            }
        }
    }

    internal sealed unsafe class _EventSource_global__Windows_Foundation_TypedEventHandler_global__Windows_Devices_Bluetooth_GenericAttributeProfile_GattWriteRequest__global__Windows_Devices_Bluetooth_GenericAttributeProfile_GattRequestStateChangedEventArgs_ : global::ABI.WinRT.Interop.EventSource<global::Windows.Foundation.TypedEventHandler<global::Windows.Devices.Bluetooth.GenericAttributeProfile.GattWriteRequest, global::Windows.Devices.Bluetooth.GenericAttributeProfile.GattRequestStateChangedEventArgs>>
    {
        private static readonly bool initialized = global::WinRT.GenericTypeInstantiations.Windows_Foundation_TypedEventHandler_2_Windows_Devices_Bluetooth_GenericAttributeProfile_GattWriteRequest__Windows_Devices_Bluetooth_GenericAttributeProfile_GattRequestStateChangedEventArgs.EnsureInitialized();

        internal _EventSource_global__Windows_Foundation_TypedEventHandler_global__Windows_Devices_Bluetooth_GenericAttributeProfile_GattWriteRequest__global__Windows_Devices_Bluetooth_GenericAttributeProfile_GattRequestStateChangedEventArgs_(IObjectReference obj,
        delegate* unmanaged[Stdcall]<System.IntPtr, System.IntPtr, WinRT.EventRegistrationToken*, int> addHandler,
        delegate* unmanaged[Stdcall]<System.IntPtr, WinRT.EventRegistrationToken, int> removeHandler, int index) : base(obj, addHandler, removeHandler, index)
        {
            _ = initialized;
        }

        protected override ObjectReferenceValue CreateMarshaler(global::Windows.Foundation.TypedEventHandler<global::Windows.Devices.Bluetooth.GenericAttributeProfile.GattWriteRequest, global::Windows.Devices.Bluetooth.GenericAttributeProfile.GattRequestStateChangedEventArgs> handler) =>
        global::ABI.Windows.Foundation.TypedEventHandler<global::Windows.Devices.Bluetooth.GenericAttributeProfile.GattWriteRequest, global::Windows.Devices.Bluetooth.GenericAttributeProfile.GattRequestStateChangedEventArgs>.CreateMarshaler2(handler);

        protected override global::ABI.WinRT.Interop.EventSourceState<global::Windows.Foundation.TypedEventHandler<global::Windows.Devices.Bluetooth.GenericAttributeProfile.GattWriteRequest, global::Windows.Devices.Bluetooth.GenericAttributeProfile.GattRequestStateChangedEventArgs>> CreateEventSourceState() =>
        new EventState(ObjectReference.ThisPtr, Index);

        [global::WinRT.WinRTExposedType]
        private sealed class EventState : global::ABI.WinRT.Interop.EventSourceState<global::Windows.Foundation.TypedEventHandler<global::Windows.Devices.Bluetooth.GenericAttributeProfile.GattWriteRequest, global::Windows.Devices.Bluetooth.GenericAttributeProfile.GattRequestStateChangedEventArgs>>
        {
            public EventState(System.IntPtr obj, int index)
            : base(obj, index)
            {
            }

            protected override global::Windows.Foundation.TypedEventHandler<global::Windows.Devices.Bluetooth.GenericAttributeProfile.GattWriteRequest, global::Windows.Devices.Bluetooth.GenericAttributeProfile.GattRequestStateChangedEventArgs> GetEventInvoke()
            {
                return (global::Windows.Devices.Bluetooth.GenericAttributeProfile.GattWriteRequest sender, global::Windows.Devices.Bluetooth.GenericAttributeProfile.GattRequestStateChangedEventArgs args) =>
                {
                    var targetDelegate = TargetDelegate;
                    if (targetDelegate is null)
                    {
                        return ;
                    }
                    targetDelegate.Invoke(sender, args);
                };
            }
        }
    }

    internal sealed unsafe class _EventSource_global__Windows_Foundation_TypedEventHandler_global__Windows_Devices_Bluetooth_Advertisement_BluetoothLEAdvertisementPublisher__global__Windows_Devices_Bluetooth_Advertisement_BluetoothLEAdvertisementPublisherStatusChangedEventArgs_ : global::ABI.WinRT.Interop.EventSource<global::Windows.Foundation.TypedEventHandler<global::Windows.Devices.Bluetooth.Advertisement.BluetoothLEAdvertisementPublisher, global::Windows.Devices.Bluetooth.Advertisement.BluetoothLEAdvertisementPublisherStatusChangedEventArgs>>
    {
        private static readonly bool initialized = global::WinRT.GenericTypeInstantiations.Windows_Foundation_TypedEventHandler_2_Windows_Devices_Bluetooth_Advertisement_BluetoothLEAdvertisementPublisher__Windows_Devices_Bluetooth_Advertisement_BluetoothLEAdvertisementPublisherStatusChangedEventArgs.EnsureInitialized();

        internal _EventSource_global__Windows_Foundation_TypedEventHandler_global__Windows_Devices_Bluetooth_Advertisement_BluetoothLEAdvertisementPublisher__global__Windows_Devices_Bluetooth_Advertisement_BluetoothLEAdvertisementPublisherStatusChangedEventArgs_(IObjectReference obj,
        delegate* unmanaged[Stdcall]<System.IntPtr, System.IntPtr, WinRT.EventRegistrationToken*, int> addHandler,
        delegate* unmanaged[Stdcall]<System.IntPtr, WinRT.EventRegistrationToken, int> removeHandler, int index) : base(obj, addHandler, removeHandler, index)
        {
            _ = initialized;
        }

        protected override ObjectReferenceValue CreateMarshaler(global::Windows.Foundation.TypedEventHandler<global::Windows.Devices.Bluetooth.Advertisement.BluetoothLEAdvertisementPublisher, global::Windows.Devices.Bluetooth.Advertisement.BluetoothLEAdvertisementPublisherStatusChangedEventArgs> handler) =>
        global::ABI.Windows.Foundation.TypedEventHandler<global::Windows.Devices.Bluetooth.Advertisement.BluetoothLEAdvertisementPublisher, global::Windows.Devices.Bluetooth.Advertisement.BluetoothLEAdvertisementPublisherStatusChangedEventArgs>.CreateMarshaler2(handler);

        protected override global::ABI.WinRT.Interop.EventSourceState<global::Windows.Foundation.TypedEventHandler<global::Windows.Devices.Bluetooth.Advertisement.BluetoothLEAdvertisementPublisher, global::Windows.Devices.Bluetooth.Advertisement.BluetoothLEAdvertisementPublisherStatusChangedEventArgs>> CreateEventSourceState() =>
        new EventState(ObjectReference.ThisPtr, Index);

        [global::WinRT.WinRTExposedType]
        private sealed class EventState : global::ABI.WinRT.Interop.EventSourceState<global::Windows.Foundation.TypedEventHandler<global::Windows.Devices.Bluetooth.Advertisement.BluetoothLEAdvertisementPublisher, global::Windows.Devices.Bluetooth.Advertisement.BluetoothLEAdvertisementPublisherStatusChangedEventArgs>>
        {
            public EventState(System.IntPtr obj, int index)
            : base(obj, index)
            {
            }

            protected override global::Windows.Foundation.TypedEventHandler<global::Windows.Devices.Bluetooth.Advertisement.BluetoothLEAdvertisementPublisher, global::Windows.Devices.Bluetooth.Advertisement.BluetoothLEAdvertisementPublisherStatusChangedEventArgs> GetEventInvoke()
            {
                return (global::Windows.Devices.Bluetooth.Advertisement.BluetoothLEAdvertisementPublisher sender, global::Windows.Devices.Bluetooth.Advertisement.BluetoothLEAdvertisementPublisherStatusChangedEventArgs args) =>
                {
                    var targetDelegate = TargetDelegate;
                    if (targetDelegate is null)
                    {
                        return ;
                    }
                    targetDelegate.Invoke(sender, args);
                };
            }
        }
    }

}